### ISSUE TITLE
[Main] Crypto Bot stop / restart on command and exception

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#112]

**Comment by pudong1** [comment]
hi, thanks for the nice work. I can start the bot on the command line, How can I stop it? Another thing is that I can not see anything delivered from the bot to the brower using : http://localhost:6666/, where my port number is 6666? Anything wrong with that? Thanks!

**Comment by GuillaumeDSM** [comment]
Hi !
Thanks for using OctoBot !

To stop it, you can either:
* use the web interface, go to the /commands page (via the button on the very right top) or typing "/commands" in the address bar and click on the "Stop OctoBot" button
* use CTRL+C on the terminal you used to start it 
* kill the python process

To activate the web interface, you need to launch the bot with the --web argument. When doing so you will see a log info with the bot address like this (example on my computer): 
INFO     WebService           Interface successfully initialized and accessible at: http://192.168.1.14:5000.

**Comment by pudong1** [comment]
Problem solved. Thanks a lot!

可用于iOS的myMail发送


2018年7月1日 星期日 +0800 21:05 发件人 notifications@github.com  <notifications@github.com>:
