### ISSUE TITLE
Issue on raspberrypi

### ISSUE THREAD

**Issue by crayse1** [Drakkar-Software/OctoBot#1214]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : [Raspbian] 
  * Python Version: _Python 2.7.16
  * In case you are not using a binary version: Using binary.
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**
After applying executable rights to binary the file does not seem to be recognized by the OS.

**Expected behavior**
The application/binary should run. 

### Steps to reproduce:

  1. Load and Run raspberry pi 4
  2. Sudo Update/Upgrade
  3. chmod +x launcher_app_linux
4. ./launcher_app_linux
  
### Observed Results:

  * What happened?  Exec format error
  * What did you expect to happen? The application to run.

### Relevant code exceptions or logs:
 
root@raspberrypi:/home/administrator/octobot# chmod +x launcher_app_linux
root@raspberrypi:/home/administrator/octobot# ls
launcher_app_linux
root@raspberrypi:/home/administrator/octobot# ./launcher_app_linux
bash: ./launcher_app_linux: cannot execute binary file: Exec format error

**Comment by Herklos** [comment]
Hi @crayse1 ! The launcher is not compiled for raspberry architecture. If you want to run OctoBot on a raspberry you should take a look at this two installation wiki pages : 
- [Python only installation](https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only)
- [Docker installation](https://github.com/Drakkar-Software/OctoBot/wiki/With-Docker)

**Comment by Herklos** [comment]
Hi @crayse1, did you succeed to run OctoBot on raspberry ?
A new version of OctoBot is now available with full raspberry support : https://github.com/Drakkar-Software/OctoBot/wiki/OctoBot-0.4
