### ISSUE TITLE
NiceHash Exchange

### ISSUE THREAD

**Issue by crayse1** [Drakkar-Software/OctoBot#1235]
**Is your feature request related to a problem? Please describe.**
Add the Nicehash Exchange as a listed exchange for Octobot
https://docs.nicehash.com/exchange-rest/index.html

**Describe the solution you'd like**
I would like to see Nicehash added to the Exchange list for Octobot

**Describe alternatives you've considered**
Alternative is to continue use of Binance.

**Additional context**
 The NiceHash Exchange API seems to be similar in nature to the Binance API. 
Further documentation found for the Websocket.  https://docs.nicehash.com/exchange-ws/nh-ws-api.html

**Comment by GuillaumeDSM** [comment]
Hi, thanks for your issue. OctoBot exchanges are managed by https://github.com/ccxt/ccxt, you should request this exchange there. Once on ccxt, it will be automatically usable in OctoBot
