### ISSUE TITLE
web protection

### ISSUE THREAD

**Issue by shehnipoor** [Drakkar-Software/OctoBot#1241]
IM use Octobot version 4
How to enable web protection??

**Comment by GuillaumeDSM** [comment]
In the web interface settings with the next 0.4 release, it's not ready yet.

**Comment by GuillaumeDSM** [comment]
It should be released some time next week

**Comment by shehnipoor** [comment]
> In the web interface settings with the next 0.4 release, it's not ready yet.

Thank you for reply  ;-)

**Comment by Herklos** [comment]
Hi @shehnipoor, you can now test this feature with [OctoBot 0.4 beta release](https://github.com/Drakkar-Software/OctoBot/wiki/OctoBot-0.4).

**Comment by Herklos** [comment]
It's now merged on main branches.
