### ISSUE TITLE
Failed to update balance : binance

### ISSUE THREAD

**Issue by shehnipoor** [Drakkar-Software/OctoBot#1243]
In connection with · having an error:

Failed to update balance : binance {"code":-1131,"msg":"'recvWindow' must be less than 60000."}
--

**Comment by GuillaumeDSM** [comment]
Please have a look here: https://github.com/Drakkar-Software/OctoBot/wiki/Installation-Troubleshoot#time-synchronization-1

**Comment by shehnipoor** [comment]
I did that
But the problem is not solved

----------------

**Comment by shehnipoor** [comment]
> Please have a look here: https://github.com/Drakkar-Software/OctoBot/wiki/Installation-Troubleshoot#time-synchronization-1
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/38042178?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Drakkar-Software/OctoBot](https://github.com/Drakkar-Software/OctoBot)**Cryptocurrency trading bot: high frequency, daily trading, social trading, ... - Drakkar-Software/OctoBot

I did that
But the problem is not solved

**Comment by GuillaumeDSM** [comment]
This problem happens sometime on windows when using a real trader on binance, unfortunatelly this is a windows issue, there is not much we can do about it except spamming this wiki command. Sometime I also have to reboot to make it work.

**Comment by shehnipoor** [comment]
> This problem happens sometime on windows when using a real trader on binance, unfortunatelly this is a windows issue, there is not much we can do about it except spamming this wiki command. Sometime I also have to reboot to make it work.

I install the robot with a docker
Isn't that a problem with Docker?

**Comment by GuillaumeDSM** [comment]
It's a problem with the internal time server of your computer, it has to be resync

**Comment by shehnipoor** [comment]
my date on server: Sun Jun  7 11:13:18 EDT 2020

**Comment by shehnipoor** [comment]
> It's a problem with the time server your computer, it has to be resync

I used version 0.3.9
problem solved
