### ISSUE TITLE
Backtesting runs into Error TimeUpdater

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [Drakkar-Software/OctoBot#1285]
## Step 1: Have you search for this issue before posting it?

Yes, found not the same problem.

## Step 2: Describe your environment
  * OS : Raspberry Pi 4
  * Python Version: 3.7.3
  * In case you are not using a binary version:
    * Branch: 0.4.0
 
## Step 3: Describe the problem:
**Describe the bug**
OctoBot on the PI completely new set up. Backtesting started with 255 calculated runs. During the runs then the error. Error still exists.

**Expected behavior**
Actually the 255 calculations should go through.

### Relevant code exceptions or logs:
![2020-08-15 18_43_35-OctoBot und 3 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/23531655/90317124-823d5e80-df27-11ea-82e3-223fe3861b40.png)
// paste your log here
[OctoBot.log](https://github.com/Drakkar-Software/OctoBot/files/5079161/OctoBot.log)

**Comment by ChristianFeldmannHamm** [comment]
After a restart of the OctoBot the error is gone for now.

**Comment by Herklos** [comment]
Hi @ChristianFeldmannHamm, thanks for report. I look at your OctoBot.log file. It seems that the ADX Evaluator failed during its computation of the adx indicator. I'll investigate on this issue. This is probably due to a lack of OHLCV data from the backtesting file.

**Comment by GuillaumeDSM** [comment]
Hi @ChristianFeldmannHamm !
This ADX isssue is now fixed, thanks !
You can either 
- Get the fix now by replacing your `tentacles/Evaluator/TA/momentum_evaluator/momentum_evaluator.py` content by this one https://github.com/Drakkar-Software/OctoBot-Tentacles/blob/0.4.0/Evaluator/TA/momentum_evaluator/momentum_evaluator.py
- Wait for the next OctoBot vers which will include it
