### ISSUE TITLE
Direct autotrading without waiting time

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [Drakkar-Software/OctoBot#1286]
**Is your feature request related to a problem? Please describe.**
If I use a strategy other than the DailyTradingMode and evaluators that need a certain amount of time (e.g. 14 days) to configure my strategy, then I have to wait this time until the actual autotrading by OctoBot starts.

**Describe the solution you'd like**
If one could now specify with a click or automatically load the necessary historical data of the corresponding time (e.g. 14 days), the autotrading by OctoBot could start immediately and without waiting time.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Herklos** [comment]
Hi @ChristianFeldmannHamm, thanks for your suggestion. You are describe a feature that loads past data (here 14 days) at OctoBot startup to initialize Evaluators properly, that's what you propose ?

**Comment by ChristianFeldmannHamm** [comment]
Yes, that is correct. You would have to see which evaluators are selected in the strategy, because there are different times (6, 10, 14, 26, etc.). Accordingly, the historical data would have to be loaded for the selected currencies.

**Comment by ChristianFeldmannHamm** [comment]
I think that would be a great solution, no more waiting.

**Comment by Herklos** [comment]
Yes it's a very interesting feature. We'll probably integrate it to the roadmap. What do you think @GuillaumeDSM?

**Comment by GuillaumeDSM** [comment]
The historical candles (max number for each exchange) are already automatically downloaded before any evaluation to be processed. I'm not sure I understand.
Or you mean a strategy (for example with an internal database requiring at least 14 days of run to be used and that can't be filled by something else that this strategy) for which it would be possible to save this database and use it directly on the next start of the bot instead of having to wait these 14 days for it to populate the new database ? 
=> Some kind of strategy-scoped database that stores strategy specific data through OctoBot sessions ?

**Comment by ChristianFeldmannHamm** [comment]
Hmm, I have a problem of understanding. For example, if I use an evaluator that calculates the average over 14 days to work (RSI), do I have to wait these 14 days before my strategy starts properly or is historical data used to calculate the current values directly?

**Comment by GuillaumeDSM** [comment]
Lets day your activated startegy requires 3 time frames: 1h, 4h and 1d, then the workflow will be the following:
1. OctoBot starts
2. For each time time frame:
    1. OctoBot fetches the historical data (500 candles on binance)
    2. When data are available, the 1st evaluation is trigger (with possibility of using all this data)
    3. The next refresh time is scheduled (in approx an hour for the 1h time frame, etc)
3. Once every required evaluator on every required timeframe has be refreshed: the strategy is waken, up and gives its evluation
4. The trading more receives the strategy evaluation and (maybe) creates an order

**Comment by ChristianFeldmannHamm** [comment]
I think then this is already implemented. Thanks for the information.
