### ISSUE TITLE
Why is there no sale?

### ISSUE THREAD

**Issue by Sascha321** [Drakkar-Software/OctoBot#1300]
Hello, there are always new orders created, but they are canceled again after a short time, can someone tell me why?

thank you

octo-bot08121971, [27.08.20 00:15]
[Real Trader] Order(s) creation

BUY_LIMIT: 0.12653 ETH at 381.59 USDT binance 08-27 00:15
octo-bot08121971, [27.08.20 02:55]
[Real Trader] Order(s) canceled :

BUY_LIMIT: 0.12634 ETH at 382.14 USDT binance 08-26 23:50
octo-bot08121971, [27.08.20 02:55]
[Real Trader] Order(s) canceled :

BUY_LIMIT: 0.12653 ETH at 381.59 USDT binance 08-27 00:15
octo-bot08121971, [27.08.20 02:55]
[Real Trader] Order(s) creation

BUY_LIMIT: 0.12629 ETH at 382.25 USDT binance 08-27 02:55
octo-bot08121971, [27.08.20 03:10]
[Real Trader] Order(s) canceled :

BUY_LIMIT: 0.12629 ETH at 382.25 USDT binance 08-27 02:55
octo-bot08121971, [27.08.20 03:10]
[Real Trader] Order(s) creation

BUY_LIMIT: 0.12654 ETH at 381.68 USDT binance 08-27 03:10
octo-bot08121971, [27.08.20 04:00]
[Real Trader] Order(s) creation

STOP_LOSS: 0.11750232 ETH at 0.03267 BTC coinbasepro 08-27 04:00
SELL_LIMIT: 0.11750232 ETH at 0.03429 BTC coinbasepro 08-27 04:00
octo-bot08121971, [27.08.20 04:20]
[Real Trader] Order(s) canceled :

STOP_LOSS: 0.11750232 ETH at 0.03267 BTC coinbasepro 08-27 04:00
SELL_LIMIT: 0.11750232 ETH at 0.03429 BTC coinbasepro 08-27 04:00
octo-bot08121971, [27.08.20 05:25]
[Real Trader] Order(s) canceled :

BUY_LIMIT: 0.12654 ETH at 381.68 USDT binance 08-27 03:10
octo-bot08121971, [27.08.20 05:28]
[Real Trader] Order(s) canceled :

BUY_LIMIT: 0.1275 ETH at 378.79 USDT binance 08-27 05:25

**Comment by Herklos** [comment]
Hi @Sascha321. Octobot creates orders on signals, if this signal expires and if the order was not filled the order is canceled. Is it clearer for you?

**Comment by Sascha321** [comment]
Hello Herklos, yes I understand that and it was clear to me, but why is the order not being executed, does that have something to do with the errors in the log? I thought OctoBot is doing the order itself or is he just doing the order? do I have to place the order manually?

**Comment by Sascha321** [comment]
Hello, I am looking for a strategy at OctoBot where he buys and if the bought currency is then worth 0.2% more, sells it again, which strategy is that?

**Comment by Herklos** [comment]
> Hello Herklos, yes I understand that and it was clear to me, but why is the order not being executed, does that have something to do with the errors in the log? I thought OctoBot is doing the order itself or is he just doing the order? do I have to place the order manually?

The order is not executed because the exchange price didn't hit the expected limit price OctoBot calculated for these orders. You don't have to place order manually, you can increase `risk` value when the market has low volatility to increase order filling probability.

**Comment by Herklos** [comment]
> Hello, I am looking for a strategy at OctoBot where he buys and if the bought currency is then worth 0.2% more, sells it again, which strategy is that?

It's a good idea, we don't have a strategy that is doing what you explained yet. But  we are interested to develop it in the near future. Can you give us more details about this strategy ?

**Comment by Sascha321** [comment]
OctoBot makes 4 query to the retailer (e.g. Bitfinex) within 2 minutes. If the trend is rising, Octobot buys and waits until it reaches the set profit and then sells again. If the trend is falling, Octobot does nothing. This strategy would only be for rising prices, but since the fluctuations are always very high, there is still a lot to be gained there.

**Comment by GuillaumeDSM** [comment]
The dip analyser strategy is doing something similar except that it looks for local dips to buy and then sets sell targets for this buy, I suggest you give it a try in backtesting
