### ISSUE TITLE
starting portfolio conf not working in Trader Simulator 

### ISSUE THREAD

**Issue by diododias** [Drakkar-Software/OctoBot#1349]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment
  * OS : docker 
  * Python Version: docker image python:3.7.4-slim
  * In case you are not using a binary version:
    * Branch: Master 
    * Last Commit ID: 0d65a1bc1712823684aa0532d4b9177cd2e9bc17
 
## Step 3: Describe the problem:
when change the starting-portfolio configuration, in portfolio page, BTC is fixed in 10 and USDT is fixed in 10000.
Even after changing configuration and restart octobot.
Trader Simulator is working in this fixed values and i want to change the values to learning more about octobot.

BTC values working fine in backtesting mode, but USDT have same problem.

**Expected behavior**
I want to change configuration of portfolio to use in Trader Simulator, and configuration reflect in portfolio page.

### Steps to reproduce:

  1. change starting-portfolio
  2. set BTC value to minimal allowed: 0.01, save and restart
  3. check portfolio values is not same in starting-portfolio
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 
```
// paste your log here
```

**Comment by Herklos** [comment]
Hi @diododias, thanks for your report. What docker image are you using?

**Comment by diododias** [comment]
i used this docker-compose.yml

```version: "3"
volumes:
  octobot:
services:
  octobot:
    container_name: octobot
    image: drakkarsoftware/octobot:0.4.0
    volumes:
       - ./logs:/octobot/logs
       - ./tentacles:/octobot/tentacles
       - ./user:/octobot/user
    ports:
       - 8888:5001
    restart: always
```

**Comment by Herklos** [comment]
Thanks, I'll try to reproduce your issue

**Comment by diododias** [comment]
I tried build a Dockerfile, changing starting-portfolio config in _config/default_config.json_, this values is reflected to portfolio successfully.
guess have an problem to get user config and merge with default configuration.

**Comment by Herklos** [comment]
I just tried to change 10 BTC to 100 BTC and I got the expected result : 100 BTC, 100 ETH...
![image](https://user-images.githubusercontent.com/10454670/97151355-b034ef80-176f-11eb-99c5-45abbc7ad623.png)
Can you give me more detail ?

**Comment by diododias** [comment]
Try change values in front-end. Try minimal values

starting-portfolio config:
![image](https://user-images.githubusercontent.com/19940445/97167638-eb322580-1765-11eb-9159-f8c3168f17cf.png)

after save and restart, portfolio continue the same was in the default configuration (BTC is 0.008 like i filled in default config)
![image](https://user-images.githubusercontent.com/19940445/97167700-043ad680-1766-11eb-910f-4bc915f32bff.png)

And backtesting USDT is fixed in 10000
when i change values to 10, 100 or 1000 USDT continue 10000
![image](https://user-images.githubusercontent.com/19940445/97168085-9fcc4700-1766-11eb-926f-4b6c14440284.png)

I have this problems with starting-portfolio in front-end configuration
i expect help you understand me
sorry any english error, is not my native language

**Comment by diododias** [comment]
please, close this bug.

I tried with drakkarsoftware/octobot:0.4.0-alpha23  image and run successfully.

docker hub latest tag can be updated to 0.4.0 alpha23 image
