### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by blondie63** [Drakkar-Software/OctoBot#1477]
Can you publish your image here: https://registry.hub.docker.com/ ?

**Comment by Herklos** [comment]
Hi @blondie63, it's already available at https://hub.docker.com/r/drakkarsoftware/octobot

**Comment by Herklos** [comment]
You should check https://github.com/Drakkar-Software/OctoBot/wiki/With-Docker

**Comment by blondie63** [comment]
ok thanks, the strange thing is that searching "OctoBot" i've no result..

**Comment by Herklos** [comment]
@blondie63 No problem, don't hesitate if you have any other question
