### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by GodAdin** [Drakkar-Software/OctoBot#1485]
I used this command: 
`docker run -itd --name OctoBot -p 80:5001 drakkarsoftware/octobot:0.4.0-stable`

The bot works but I can't find the folder where I installed it to make changes. Where can I find him?
I use ubuntu 20.04

**Comment by Herklos** [comment]
Hi @GodAdin, you can use `docker volume ls` to list docker volumes on your machine. Volumes folder are located in /var/lib/docker.

**Comment by GodAdin** [comment]
I found but I don't see `user / config.json` to enable telegram. Where can I find this file?

**Comment by Herklos** [comment]
@GodAdin you can use `docker inspect -f '{{ .Mounts }}' OctoBot` to know where each folders are mounted
