### ISSUE TITLE
A problem with the web interface

### ISSUE THREAD

**Issue by Cherecho** [Drakkar-Software/OctoBot#1515]
First of all I apologize if I'm being silly writing this, but I can't solve it and I don't know why, the web interface runs perfectly but when I try to change something inside it it doesn't let me, it lets me navigate perfectly but when I try to add for example an exchange I can choose it but when I click on add nothing happens, the same if I try to delete the "binance" presset with the remove button, or in the "Your OctoBot" tab the buttons don't work for me :(

Im using: Python 3.8.7 and and installed it with just python
![image](https://user-images.githubusercontent.com/48016628/106978395-7c00a000-675c-11eb-8bd1-5e01c979aacd.png)
![image](https://user-images.githubusercontent.com/48016628/106978418-891d8f00-675c-11eb-9653-a7240cd523bc.png)
the problem is that the web interface is not able to connect to Octobot, but any idea how to solve it?

**Comment by Cherecho** [comment]
the problem is that the web interface is not able to connect to Octobot, but any idea how to solve it?

**Comment by GuillaumeDSM** [comment]
When opening the browser terminal (F12), do you get any error on page loading ?

**Comment by Herklos** [comment]
Hi @Cherecho, is it fixed now?
