### ISSUE TITLE
Config File is not identifying on docker installation.

### ISSUE THREAD

**Issue by Thilakesh** [Drakkar-Software/OctoBot#1516]
I have facing the issue that the config file was not recognized by docker. It creating the default file for config and I don't get that file. Can you please check on that.
![Screenshot_2](https://user-images.githubusercontent.com/50583136/107084570-3c4dbd00-681d-11eb-869b-20f8b81e4597.png)

**Comment by Herklos** [comment]
Hi @Thilakesh, what's your issue ? You want to use an already created config file in your docker or access the newly created config file ?

**Comment by Thilakesh** [comment]
![image](https://user-images.githubusercontent.com/50583136/107109404-362ffe80-6866-11eb-8673-f6aa6523b0ab.png)

I have done this as shown in above screenshot.

Copy the default_config from GitHub (https://github.com/Drakkar-Software/OctoBot/blob/master/octobot/config/default_config.json) and paste on my user/config and rename it to config. Still the file is not recognized by docker.

![Screenshot_3](https://user-images.githubusercontent.com/50583136/107109444-a8a0de80-6866-11eb-81a5-69376514ff29.png)

**Comment by Herklos** [comment]
You may prefer to use Web interface to edit your config file. You should let OctoBot create the default config file and then you'll be able to modify your configuration properly.

**Comment by Thilakesh** [comment]
No I have error on Python installation.

Can you please tell me how to configure that config file will recognized on docker please?

**Comment by Herklos** [comment]
You mean a local file (a file on your docker host) ?

**Comment by Herklos** [comment]
You mean a local file (a file on your docker host) ?

**Comment by Thilakesh** [comment]
If we change the docker config file it will work?

**Comment by Thilakesh** [comment]
And can you please tell where the OctoBot create the default config file?

**Comment by Herklos** [comment]
> And can you please tell where the OctoBot create the default config file? I cant find that

It's located in **user/profiles/default/profile.json**.

**Comment by Thilakesh** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/50583136/107126767-c35f6b80-68d7-11eb-9368-01445d28e247.png)

I have to change this config file on C drive.

**Comment by Herklos** [comment]
> ![Screenshot_4](https://user-images.githubusercontent.com/50583136/107126767-c35f6b80-68d7-11eb-9368-01445d28e247.png)
> 
> I have to change this config file on C drive.

Yes
