### ISSUE TITLE
feature : backtesting - bot profitability by crypto

### ISSUE THREAD

**Issue by valouvaliavlo** [Drakkar-Software/OctoBot#1535]
Hi, what do you think about have the bot profitability on each crypto ?

**Comment by valouvaliavlo** [comment]
I think have this in general, not only in backtesting would be great

**Comment by Herklos** [comment]
Hi @valouvaliavlo, it would be really helpful to have such information.

**Comment by valouvaliavlo** [comment]
HI, 
for example :
trade 1 (BNB/USDT): open at 100$, close at 200$ : 100% profit
trade 2 (BTC/USDT): open at 40000$, close at 30000$ : 20% loss
trade 3 (BNB/USDT): open at 200$, close at 220$: 20% profit
trade 4 (BTC/USDT): open at 30000$, close at 33000: 10% profit

BNB/USDT bot average profitability : 100 + 20 / 2  = 60%
BTC/USDT bot average profitability : -20 + 10 / 2 = 5%

if we launch a backtest on several crypto the strategy will be more or less good depending on the profile of the crypto (volatility, bear, bull ...)

**Comment by valouvaliavlo** [comment]
either an average of the profitability of the trade or a weighted average which would have a value that would depend on the value put on the trade
