### ISSUE TITLE
Error while fetching portfolio from Kraken

### ISSUE THREAD

**Issue by tbe** [Drakkar-Software/OctoBot#1548]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment
  * OS : Linux/Docker
  * Version: Current stable

 
## Step 3: Describe the problem:
**Describe the bug**
The Portfolio stays empty, but should not.

**Expected behavior**

OctoBot is able to fetch the Portfolio

### Steps to reproduce:

  1. Configure Kraken as Exchange
  2. Fetch Portfolio
  
### Relevant code exceptions or logs:
 
```
octobot_1  |  2021-02-19 17:36:54,654 ERROR    root                   File "octobot_trading/personal_data/portfolios/portfolio.py", line 195, in octobot_trading.personal_data.portfolios.portfolio.Portfolio._parse_currency_balance
octobot_1  | NoneType: None
octobot_1  |  2021-02-19 17:36:54,655 ERROR    root                 <class 'TypeError'>: must be real number, not NoneType
octobot_1  | NoneType: None
octobot_1  | Exception ignored in: 'octobot_trading.personal_data.portfolios.portfolio.Portfolio.update_portfolio_from_balance'
octobot_1  | Traceback (most recent call last):
octobot_1  |   File "octobot_trading/personal_data/portfolios/portfolio.py", line 195, in octobot_trading.personal_data.portfolios.portfolio.Portfolio._parse_currency_balance
octobot_1  | TypeError: must be real number, not NoneType
```

**Comment by Herklos** [comment]
Hi @tbe, thanks for reporting, we'll investigate your issue.

**Comment by Herklos** [comment]
It now fixed in dev version, it will be available in the next release
