### ISSUE TITLE
[Documentation] Add documentation for evaluator management classes

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#156]
abstract_evaluator.py
cryptocurrency_evaluator.py
evaluator.py
evaluator_creator.py
evaluator_final.py
evaluator_matrix.py
evaluator_order_creator.py
evaluator_threads_manager.py
symbol_evaluator.py

**Comment by Herklos** [comment]
Can be done with [this](https://github.com/sphinx-doc/sphinx)

**Comment by GuillaumeDSM** [comment]
close and add doc in 0.4 ?

**Comment by Herklos** [comment]
Yes !
