### ISSUE TITLE
[Feature] enable twitter in read-only evaluation mode, disabling publish mode feature

### ISSUE THREAD

**Issue by WarriorWithin** [Drakkar-Software/OctoBot#1560]
Log keeps reporting "Failed to send tweet" and "Tweet is not sent" because my twitter api key is in read only mode. I setted it this way because I wish like I could set it to operate only as TwitterNewsEvaluator and not as publisher. 

In top of that, Twitter is very cautious with apps which are not read only mode and I dont wish like bother them with write permissions in order not get banned for spam or "business usage".

Solution would be: allow in interface tab to disable Twitter notifications and use social only for evaluations, ignoring completely the send tweet part using bot etc

**Comment by GuillaumeDSM** [comment]
Hi @WarriorWithin 

You can disable twitter notifications by not listing it in the notification page
![image](https://user-images.githubusercontent.com/9078616/108882552-d0cd6300-7604-11eb-98b7-88e83281ebc5.png)

**Comment by WarriorWithin** [comment]
that's great!
