### ISSUE TITLE
 Could not find a version that satisfies the requirement OctoBot-Commons==1.5.4

### ISSUE THREAD

**Issue by muhammetbalci** [Drakkar-Software/OctoBot#1583]
I'm trying to install with python. There is python 3.9.2 in my server (centos).  This error displays after pip install command. 

```
# python3 -m pip install -Ur requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting cython==0.29.21 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/19/49/91ebe4a00bf894d08dd                                                  9680cd9dfb05936eb2848eebd9402b43885aa74cf/Cython-0.29.21-cp36-cp36m-manylinux1_x 86_64.whl
Collecting OctoBot-Commons==1.5.4 (from -r requirements.txt (line 5))
  Could not find a version that satisfies the requirement OctoBot-Commons==1.5.4 (from -r requirements.txt (line 5)) (from versions: )
No matching distribution found for OctoBot-Commons==1.5.4 (from -r requirements.txt (line 5))
```

**Comment by Herklos** [comment]
Hi @muhammetbalci, OctoBot is not supporting python 3.9 for now, you should use python 3.8.

**Comment by muhammetbalci** [comment]
I've changed with python 3.8.8 and the same problem still continue. Should be 3.8.0?

**Comment by Herklos** [comment]
> I've changed with python 3.8.8 and the same problem still continue. Should be 3.8.0?

A `No matching distribution found for OctoBot-Commons==1.5.4` error message appears with python 3.8 ?

**Comment by muhammetbalci** [comment]
Yes, exactly same error appers.

**Comment by Herklos** [comment]
> Yes, exactly same error appers.

What is the ouput of `python3 --version` ?

**Comment by muhammetbalci** [comment]
Yes, this is  the problem. Version is 3.6.8. I removed it before still python3 calling the 3.6.8. Now I changed the default with alias and doesn't work. Apparently it's not about Octobot, I should clean the other python3 versions. Thanks!

**Comment by Herklos** [comment]
Don't hesitate to open a new issue if you have any other problem.

**Comment by muhammetbalci** [comment]
Successfully it has installed, but now the problem is `python3 start.py tentacles --install --all` which is
`ModuleNotFoundError: No module named '_sqlite3'`

**Comment by Herklos** [comment]
Strange issue, you should try to run `sudo yum install sqlite-devel` before `python3 start.py tentacles --install --all`

**Comment by muhammetbalci** [comment]
It was already installed. But I found the problem. I removed all python 3.6, 3.8 and 3.9 files on usr/local/ and re-install. It works very well!
I can access ipaddress:5001 until I close the ssh console. How can I access even if the terminal is not open?

**Comment by Herklos** [comment]
> It was already installed. But I found the problem. I removed all python 3.6, 3.8 and 3.9 files on usr/local/ and re-install. It works very well!
> I can access ipaddress:5001 until I close the ssh console. How can I access even if the terminal is not open?

Great ! 
You should use [`screen`](https://www.howtogeek.com/662422/how-to-use-linuxs-screen-command/) before your `python3 start.py` command. Like `screen python3 start.py` to run OctoBot in a different session from your ssh.
