### ISSUE TITLE
feature - Sell only feature in dailytradingmode

### ISSUE THREAD

**Issue by WarriorWithin** [Drakkar-Software/OctoBot#1597]
Sometimes, the market becomes blatantly bearish or bullish in BTC terms (no more sideways), so alts may start a pretty hard downfall. 

This issue can be addressed by manual tweak (or button switch) that allow user to choose whether or not he wish octobot to act as stand alone seller without making buys anymore, till the buy feature is manually restored.

**Comment by Herklos** [comment]
Hi @WarriorWithin, thanks for your proposition, we have already developed this feature, it'll be available in the next version.

**Comment by WarriorWithin** [comment]
amazing  @Herklos! Thanks
