### ISSUE TITLE
[Question] [Docs] What does the "Load-Trade-History" option do?

### ISSUE THREAD

**Issue by gabriel-milan** [Drakkar-Software/OctoBot#1622]
Hi there!

On trading settings, there are only two boolean variables I can set:

- Enabled
- Load-Trade-History

Unfortunately, I haven't found anything on [the docs](https://docs.octobot.online/pages/Trader.html) about the Load-Trade-History variable. Can you please tell me what is that about? I'm at version 0.4.0b6 running on a RPi.

**Comment by Herklos** [comment]
Thanks @WarriorWithin for the answer, we will add this to the doc. It's ok @gabriel-milan ? Can we close the issue ?

**Comment by gabriel-milan** [comment]
Sure, thank you guys!
