### ISSUE TITLE
Binance is overloaded by 47%

### ISSUE THREAD

**Issue by edebie** [Drakkar-Software/OctoBot#1656]
I got this warning "Binance exchange is overloaded by 47%. Binance capacity is 45 simultaneous traded pair/time frame couples".

Any suggestions how to handle that?

**Comment by dbstraffin** [comment]
Binance rate limits the rest api by IP address.  You need to reduce the number of currencies and/or time frames.  Your currencies x time frames > 45.  

So if you have 20 currencies enabled and your strategy is using 1m, 30m and 1h, that's 60.

**Comment by edebie** [comment]
I tried to enable web socket in the config file but still having the same error. Any suggestions to lift this restriction?

**Comment by dbstraffin** [comment]
I tried enabling web-sockets as well, but still got that warning.  The docs list web-sockets as being 80% for Binance.  I use Binance.us and didn't see anything in the logs that mention websockets, so I figured it wasn't working.

I tried poking around in the code but wasn't able to easily tell if web sockets were being used or not.   Maybe it is and that warning is just not aware of websockets?

**Comment by Herklos** [comment]
> I tried enabling web-sockets as well, but still got that warning. The docs list web-sockets as being 80% for Binance. I use Binance.us and didn't see anything in the logs that mention websockets, so I figured it wasn't working.
> 
> I tried poking around in the code but wasn't able to easily tell if web sockets were being used or not. Maybe it is and that warning is just not aware of websockets?

Hi @dbstraffin @edebie, as you say the best way to deal with binance overloading is to use a websocket. To activate a websocket on an exchange, OctoBot needs to have the exchange websocket module installed. For now there is no websocket available. We are developing Binance websocket, we hope it will be available soon.

**Comment by Herklos** [comment]
Binance websocket is now available.
