### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by mertdogan** [Drakkar-Software/OctoBot#1672]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : Windows Server 2012
  * Python Version: 3.8.9
  * In case you are not using a binary version:
    * Branch: Master
    * Last Commit ID: ?
 
## Step 3: Describe the problem:
**Describe the bug**

After 
python -m pip install -Ur requirements.txt
 command , installation failed at 
 
Building wheels for collected packages: tulipy
  Building wheel for tulipy (PEP 517) ... 

with error as 

 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

but i allready installed Visual Studio C++ 2015 Redistributable (x86), Visual Studio C++ 2015 Redistributable (x64), Visual Studio C++ Redistributable (x86), Microsoft Build Tools 2015 but installation process failes as screen shot.

**Expected behavior**
Simply run commands:

git clone https://github.com/Drakkar-Software/OctoBot.git
cd OctoBot
python -m pip install -Ur requirements.txt
python start.py

### Steps to reproduce:

  1. Open cmd on Windows Server 2012 machine
  2. Run command above
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
![image](https://user-images.githubusercontent.com/1324617/116381044-32849600-a81d-11eb-9626-fc8b3d30c99a.png)
 
![image](https://user-images.githubusercontent.com/1324617/116382431-93609e00-a81e-11eb-8c10-6f7e388616a3.png)

```
Building wheels for collected packages: tulipy
  Building wheel for tulipy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python\Python38\python.exe' 'C:\Python\Python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel C:\Users\ADMINI~1\AppData\Local\Temp\2\tmpmt_kvlh5'
       cwd: C:\Users\Administrator\AppData\Local\Temp\2\pip-install-46sco1et\tulipy_7c70c3b294cb4eaf87bf52b74b643b58
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\tulipy
  copying tulipy\__init__.py -> build\lib.win-amd64-3.8\tulipy
  running build_ext
  skipping 'tulipy/lib\__init__.c' Cython extension (up-to-date)
  building 'tulipy.lib' extension
  C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-tf0y56oh\overlay\Lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsof
t C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for tulipy
Failed to build tulipy
ERROR: Could not build wheels for tulipy which use PEP 517 and cannot be installed directly
```

**Comment by Herklos** [comment]
Hi @mertdogan, I am developing on Linux, I can't help you. Do you have any idea @GuillaumeDSM  ?

**Comment by GuillaumeDSM** [comment]
It looks like you are missing some dependencies. It's weird because usually precompiled versions of the lib are used but you might have a different than normal setup. They way to fix it is to install ms visual studio to get a c++ compiler and python will automatically recompile the libs in a way that will be compatible with your setup

**Comment by mertdogan** [comment]
I can't find any solution unless install Visual Studio 2015 community edition.

I installed VSCE2015 from ISO (web installer not working also) and everything compiled successfully.

VS 2015 Build Tools is not enough alone. Thanks.

**Comment by Herklos** [comment]
@mertdogan did you find a fix?

**Comment by mertdogan** [comment]
Yes i installed VSCE2015 and everything fixed.

**Comment by Herklos** [comment]
Great!
