### ISSUE TITLE
Error: 'NoneType' object has no attribute 'status_code' (AttributeError). More details in logs.

### ISSUE THREAD

**Issue by scnclyq** [Drakkar-Software/OctoBot#1735]

**Comment by GuillaumeDSM** [comment]
Hi @scnclyq,
Thanks for reporting the issue, could you please include the log files of the execution with this error please ? This will greatly help to figure out what is happening.

**Comment by scnclyq** [comment]
I cannot provide log information for the issues,because,when I changed the API again, the new error message was ：
<Error: sequence item 0: expected str instance, NoneType found (TypeError).>
[logs_export.zip](https://github.com/Drakkar-Software/OctoBot/files/6721312/logs_export.zip)

**Comment by GuillaumeDSM** [comment]
Thanks for sharing your logs, the issue will be fixed in the next version !
I also fixed an issue regarding invalid backtesting data files that could prevent display

**Comment by scnclyq** [comment]
[Error 'NoneType' .zip](https://github.com/Drakkar-Software/OctoBot/files/6723508/Error.NoneType.zip)
This is log information about  <Error: 'NoneType' object has no attribute 'status_code' (AttributeError)>.

**Comment by GuillaumeDSM** [comment]
fixed in https://github.com/Drakkar-Software/OctoBot/releases/tag/0.4.0b12
