### ISSUE TITLE
Custom Port For Python

### ISSUE THREAD

**Issue by RahmatAliMalik5** [Drakkar-Software/OctoBot#1800]
Can we provide a custom port when running Python? I am trying to deploy Octobot using Phussion Passenger for Apache. Phussion Passenger for Apache uses dynamic ports to run python. If it is available, please let me know. I have tried to find it for multiple hours.

Thanks

**Comment by Herklos** [comment]
Hello @RahmatAliMalik5, you can find how to configure web interface port here : https://docs.octobot.online/interfaces/web-interface#web-service-configuration.

**Comment by RahmatAliMalik5** [comment]
Thanks @Herklos for abrupt reply to the issue.

I have checked this page before. But in my project, I do not have a user folder. So, there is no config.json file there.

I am using `master` branch.

Is there anything, I am doing wrong?

**Comment by RahmatAliMalik5** [comment]
I can see a similar file here : `octobot/config/default_config.json`

Is that one is the file,
 you have shared reference of?

**Comment by RahmatAliMalik5** [comment]
Yes, I have found `user/config.json`. My Bad not found it in first place. But still not able to update PORT through command line. Is it possible by providing any environment variable?

**Comment by RahmatAliMalik5** [comment]
Fount it from code. `WEB_PORT=3002 python3.8 start.py` can update port through command line. Thanks @Herklos for help and saving me from spending more hours.

**Comment by Herklos** [comment]
Glad to hear your problem is resolved. Don't hesitate to create a new issue if you have any other problem.

**Comment by RahmatAliMalik5** [comment]
@Herklos Thanks
