### ISSUE TITLE
[Trading] add portfolio-locked mode

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#182]
add investor mode where bot is not sell some currencies in its conf
ex:
"locked-portfolio":{
   "VEN": 25%,
   "ETH": 10%
}
here telling to bot to buy positions when favorable on VEN and ETH up to a max of 25% of starting portfolio in VEN and 10% in ETH

**Comment by Herklos** [comment]
See issue https://github.com/Drakkar-Software/OctoBot-Tentacles/issues/5
