### ISSUE TITLE
Docker Image Raspberry ARMv7

### ISSUE THREAD

**Issue by dystopy** [Drakkar-Software/OctoBot#1864]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : [Windows, Ubuntu, Debian, Raspbian...] 
  * Docker on Raspbian
  * Python Version: _____ (`python -V`)
  * 
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**

Even if the latest image does not contain armv7 architecture, I tried to use the last known version compatible with armv7 arch with following command : 

 docker run -itd --name OctoBot -p 5001:5001 -v $(pwd)/user:/octobot/user -v $(pwd)/tentacles:/octobot/tentacles -v $(pwd)/logs:/octobot/logs drakkarsoftware/octobot:0.4.0b7

The container starts and never crash, but I'm never able to connect on 5001 port. Added to that, "docker logs OctoBot" returns following logs : 

![image](https://user-images.githubusercontent.com/31865048/137508872-6e5b885d-7a8d-46e9-8aeb-d0aa96f7f0a0.png)

Any idea why ?

Many thanks in advance!

**Comment by Herklos** [comment]
Hi, please have a look at #1857 "Due to technical difficulties armv7 docker image is no longer supported for the moment."
