### ISSUE TITLE
Pairs and timeframes combos disappear when switching the exchange on download exchange data page

### ISSUE THREAD

**Issue by juanluisbaptiste** [Drakkar-Software/OctoBot#1870]
## Step 1: Have you search for this issue before posting it?

Yes and did not found anything related to this.

## Step 2: Describe your environment
  * OS : Ubuntu
  * Official docker container, stable version 0.4.1
  * Browser: Firefox 93.0
 
## Step 3: Describe the problem:
On the download exchange data page, when I change the exchange the pairs and timeframes combos disappear. I have read on the telegram channel that some exchanges do not support the timeframes parameter but the pairs should be in all cases. For example, switching from binance to binanceus or any other those combos disappear, and switching back to binance does not bring them back either. The only way is by refreshing the page. This means that the only exchange that can be backtested is binance.

**Expected behavior**
Supported combos by exchange should be visible all the time, specially the pairs combo.

### Steps to reproduce:

  1. Open the backtesting page anc click on the download exchange data button
  2. Switch the default exhange (binance) to any from the list and see the paris and timeframes combos disappear
  3. Switch back to the default exchange (binance) and see that the combos do not appear again
  
### Observed Results:

The pairs and timeframes combos disappear.

### Relevant code exceptions or logs:

Initial state:

![Screenshot_20211028_193805](https://user-images.githubusercontent.com/2113585/139354580-7698dd3b-e5dc-4122-affc-1f8047228ea2.png)

Changing the exchange to another one:

![Screenshot_20211028_193918](https://user-images.githubusercontent.com/2113585/139354671-53532b6d-713d-4b9c-947b-7d8c5800a7dd.png)

After changing the exchange and going back to binance:

![Screenshot_20211028_193645](https://user-images.githubusercontent.com/2113585/139354484-efedc971-5a35-4bbc-a1cd-7df305259913.png)

**Comment by valouvaliavlo** [comment]
> Excellent, thanks!
> 
> Will it be available on the unstable docker image soon ?

It will be available in 0.4.2, 2-3 days
