### ISSUE TITLE
Can't install OctoBot Windows, can't repair config.json

### ISSUE THREAD

**Issue by techsoulman** [Drakkar-Software/OctoBot#1882]
Hi There, I am having a very similar problem installing as this closed issue but slightly different and the solution doesn't work.

I have uploaded a screenshot because the prompt closes moments after giving the message.

Also worth noting that no folders appear to have been created for OctoBot so I have no idea where to put config.json file, I tried creating the  Appdata/Temp/etc/etc path and adding it there and also creating an OctoBot folder in program files and adding it there but neither helped.

![Screenshot (18)](https://user-images.githubusercontent.com/16014225/140901775-af1aeb7e-7af2-49c3-b05e-c983573db3dd.png)

_Originally posted by @techsoulman in https://github.com/Drakkar-Software/OctoBot/issues/274#issuecomment-963987493_

**Comment by valouvaliavlo** [comment]
Hi @techsoulman 
Can you test to run it in another folder ?

**Comment by AhmadAlaviManesh** [comment]
i had the same problem, i couldn't fix it but i tried to use the manual installation with anaconda prompt and it work now.
i used these step from install guide in the [site](https://docs.octobot.online/installation/with-python-only):

`git clone https://github.com/Drakkar-Software/OctoBot
`
Install python packages :
` cd OctoBot
python -m pip install -Ur requirements.txt
python start.py tentacles --install --all`

and to start it:
`python start.py`

it only work from conda prompt

**Comment by techsoulman** [comment]
> Hi @techsoulman Can you test to run it in another folder ?

Thanks so much!
This worked, but I don't know why.
