### ISSUE TITLE
Portfolio fails to calculate indirect currencies

### ISSUE THREAD

**Issue by daniel-lucio** [Drakkar-Software/OctoBot#1899]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment
  * OS : Linux 
  * Python 3.8
  * In case you are not using a binary version:
    * Branch: tag 0.4.3
 
## Step 3: Describe the problem:
**Describe the bug**
Octobot fails to calculate portfolio of currencies that do not have a direct pair with the reference-market currency. Example:
gate.io does not offer SC/BTC market, but it does offer SC/USD and SC/ETH, there is also available the USD/BTC and ETH/BTC market. Octobot fails to calculate in an indirect way the SC value when BTC is the reference-market currency.

**Expected behavior**
Use indirect market to make the maths, in this example, it should be using SC/USD or SC/ETH and then USD/BTC or ETH/BTC to get an indirect value of SC when BTC is the reference market currency.

### Steps to reproduce:

  1. get gate.io configured 
  2. put some SC in your portfolio (works with simulated trading as well), more than 6000 SC as SC value is small.
  3. setup BTC as reference market currency
  4. save and restart Octobot
  5. check the logs, see how SC has 0 value
  
### Observed Results:

  * What happened?
SC has 0 BTC value market

  * What did you expect to happen?
SC should have something different than 0.

### Relevant code exceptions or logs:
Can access them on this computer, you will see this when you follow my reproduction steps
 
```
// paste your log here
```

**Comment by daniel-lucio** [comment]
![Screenshot_20211129_070404](https://user-images.githubusercontent.com/3492858/143864977-659f1c0f-eb64-4102-9f99-647e87682b91.png)

Here is the screenshot, see how SC is zero

**Comment by valouvaliavlo** [comment]
Hi @daniel-lucio,
Like there is no SB/BTC on gate.io OctoBot can't get it.

**Comment by daniel-lucio** [comment]
> Hi @daniel-lucio, Like there is no SB/BTC on gate.io OctoBot can't get it.

Did you read all my full description?

**Comment by valouvaliavlo** [comment]
> > Hi @daniel-lucio, Like there is no SB/BTC on gate.io OctoBot can't get it.
> 
> Did you read all my full description?

Ah yes, sorry !
It's an interesting idea

**Comment by Herklos** [comment]
This feature has just been released in 0.4.43 😉
