### ISSUE TITLE
Error : when displaying page: set_wakeup_fd only works in main thread (ValueError)

### ISSUE THREAD

**Issue by munsunouk** [Drakkar-Software/OctoBot#1904]
## Step 1: Have you search for this issue before posting it?
It has not reported

## Step 2: Describe your environment
  * OS : Windows
  * Python Version: 3.8.0
 
## Step 3: Describe the problem:
**Describe the bug**
I tried to configure the dailytrading mode. but when i clicked configure button it appear another one as error
![dailytrading mode](https://user-images.githubusercontent.com/52026496/146141865-892256f8-ed85-4376-af7d-ecbc12065699.png)
![error](https://user-images.githubusercontent.com/52026496/146141790-6c116c9f-1959-4fe3-b5bb-d42a307f8560.png)
and my event log is like this
![image](https://user-images.githubusercontent.com/52026496/146142164-97ecb5cf-77a2-4bf5-9b89-fd2bc75cebf7.png)

**Expected behavior**
i want solve the problem to do configure of daily trading bot

**Comment by Herklos** [comment]
Hi @MunSunouk, what's your installation method? Python or binary?
