### ISSUE TITLE
I'm hoping you can help me figure this out 

### ISSUE THREAD

**Issue by hansendm** [Drakkar-Software/OctoBot#1921]
Collecting OctoBot-Evaluators==1.6.22
  Using cached OctoBot-Evaluators-1.6.22.tar.gz (39 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ak7m1y1o/octobot-evaluators_75e26cef5f724251a0a3b7610e1bd729/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ak7m1y1o/octobot-evaluators_75e26cef5f724251a0a3b7610e1bd729/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2p2s3mxu
         cwd: /tmp/pip-install-ak7m1y1o/octobot-evaluators_75e26cef5f724251a0a3b7610e1bd729/
    Complete output (145 lines):
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    #  Lesser General Public License for more details.
    #
    #  You should have received a copy of the GNU Lesser General Public
    #  License along with this library.
    cimport async_channel.channels as channels
           ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.pxd:17:8: 'async_channel/channels.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #  Lesser General Public License for more details.
    #
    #  You should have received a copy of the GNU Lesser General Public
    #  License along with this library.
    cimport async_channel.channels as channels
    cimport async_channel.consumer as consumers
           ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.pxd:18:8: 'async_channel/consumer.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #
    #  You should have received a copy of the GNU Lesser General Public
    #  License along with this library.
    cimport async_channel.channels as channels
    cimport async_channel.consumer as consumers
    cimport async_channel.producer as producers
           ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.pxd:19:8: 'async_channel/producer.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #  License along with this library.
    cimport async_channel.channels as channels
    cimport async_channel.consumer as consumers
    cimport async_channel.producer as producers
    
    cdef class EvaluatorChannel(channels.Channel):
                                       ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.pxd:21:36: First base of 'EvaluatorChannel' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef class EvaluatorChannel(channels.Channel):
        cdef public str matrix_id
    
        cpdef list get_consumer_from_filters(self, dict consumer_filters, EvaluatorChannelConsumer origin_consumer=*)
    
    cdef class EvaluatorChannelConsumer(consumers.Consumer):
                                                ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.pxd:26:45: First base of 'EvaluatorChannelConsumer' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cpdef list get_consumer_from_filters(self, dict consumer_filters, EvaluatorChannelConsumer origin_consumer=*)
    
    cdef class EvaluatorChannelConsumer(consumers.Consumer):
        pass
    
    cdef class EvaluatorChannelProducer(producers.Producer):
                                                ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.pxd:29:45: First base of 'EvaluatorChannelProducer' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import octobot_commons.logging as logging
    
    import octobot_evaluators.constants as constants
    
    
    class EvaluatorChannelConsumer(consumers.Consumer):
                                           ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.py:29:40: First base of 'EvaluatorChannelConsumer' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        Consumer adapted for EvaluatorChannel
        """
    
    
    class EvaluatorChannelProducer(producers.Producer):
                                           ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.py:35:40: First base of 'EvaluatorChannelProducer' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        Producer adapted for EvaluatorChannel
        """
    
    
    class EvaluatorChannel(channels.Channel):
                                  ^
    ------------------------------------------------------------
    
    octobot_evaluators/evaluators/channel/evaluator_channel.py:41:31: First base of 'EvaluatorChannel' is not an extension type
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ak7m1y1o/octobot-evaluators_75e26cef5f724251a0a3b7610e1bd729/setup.py", line 89, in <module>
        ext_modules=cythonize(ext_modules, gdb_debug=CYTHON_DEBUG),
      File "/tmp/pip-install-ak7m1y1o/octobot-evaluators_75e26cef5f724251a0a3b7610e1bd729/.eggs/Cython-0.29.26-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1103, in cythonize
        cythonize_one(*args)
      File "/tmp/pip-install-ak7m1y1o/octobot-evaluators_75e26cef5f724251a0a3b7610e1bd729/.eggs/Cython-0.29.26-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1226, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: octobot_evaluators/evaluators/channel/evaluator_channel.py
    Compiling octobot_evaluators/octobot_channel_consumer.py because it changed.
    Compiling octobot_evaluators/evaluators/evaluator_factory.py because it changed.
    Compiling octobot_evaluators/evaluators/channel/evaluators.py because it changed.
    Compiling octobot_evaluators/evaluators/channel/evaluator_channel.py because it changed.
    Compiling octobot_evaluators/util/evaluation_util.py because it changed.
    Compiling octobot_evaluators/matrix/matrix.py because it changed.
    Compiling octobot_evaluators/matrix/matrices.py because it changed.
    Compiling octobot_evaluators/matrix/matrix_manager.py because it changed.
    Compiling octobot_evaluators/matrix/channel/matrix.py because it changed.
    [1/9] Cythonizing octobot_evaluators/evaluators/channel/evaluator_channel.py
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/25/57/2b447c3a3c4ae3882f04e102dde9581903ca47606ab9393a95f63cf76eb6/OctoBot-Evaluators-1.6.22.tar.gz#sha256=0aab14fa157a5649ff3d4c99a57677d13516257790f35ccf4e0332dd1e463e3e (from https://pypi.org/simple/octobot-evaluators/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement OctoBot-Evaluators==1.6.22
ERROR: No matching distribution found for OctoBot-Evaluators==1.6.22

**Comment by hansendm** [comment]
Does anyone have a clue on how to fix this error?

**Comment by GuillaumeDSM** [comment]
It looks like you are trying to install OctoBot with python 3.9. For now OctoBot is only compatible with 3.8

**Comment by hansendm** [comment]
ok..I will downgrade for now.. I thought that 3.9 would be compatible considering the syntax says (requires-python:>=3.8)
