### ISSUE TITLE
Error: object is not subscriptable (TypeError).

### ISSUE THREAD

**Issue by aldejan** [Drakkar-Software/OctoBot#1928]
Error: 'octobot_trading.personal_data.portfolios.assets.spot_asset.SpotAsset' object is not subscriptable (TypeError).
this error happens when I installed on digitalocean with basic settings

![Captura de tela 2022-02-16 133025](https://user-images.githubusercontent.com/66024189/154311276-c54b8a9d-80bc-42ba-bcd5-a71e7acc506c.png)

please help me, he is doing the normal entries, selling and buying, just does not appear the portfolio

**Comment by GoranDK2** [comment]
same error here

**Comment by lukmanfyrtio** [comment]
i have the same error here,hopefully dev cant explain how to fix this

**Comment by GuillaumeDSM** [comment]
It will be fixed at the next release
