### ISSUE TITLE
DigitalOcean - Invalid app spec file

### ISSUE THREAD

**Issue by omalisson** [Drakkar-Software/OctoBot#1934]
Hi!

I just tried to create a new app using the Octo page link and I get this error information:

![image](https://user-images.githubusercontent.com/35525083/157724319-b0a6b9ac-5096-4c92-9980-052c04a0fe48.png)

How to solve this?

**Comment by Herklos** [comment]
Hi @omalisson! Thanks for reporting. Digital ocean deployments are no longer supported, please use [OctoBot-Cloud](https://www.octobot.cloud/).
