### ISSUE TITLE
Build 0.4.3 broken on MacOS 10.15.4 : Python3 = 3.8.13 Jinja2 = 2.11.3 MarkupSafe=2.1.1

### ISSUE THREAD

**Issue by danieljamesbertrand** [Drakkar-Software/OctoBot#1957]
using the tarball Octobot-0.4.3

ERROR on python3 start.py

    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)

DETAILS:

python3 -V
Python 3.8.13

pip list
Package                   Version
------------------------- -----------
aioboto3                  9.2.2
aiobotocore               1.4.2
aiodns                    3.0.0
aiofile                   3.7.4
aiofiles                  0.6.0
aiohttp                   3.8.0
aioitertools              0.10.0
aiosignal                 1.2.0
aiosqlite                 0.16.1
APScheduler               3.6.3
async-channel             2.0.12
async-generator           1.10
async-timeout             4.0.2
asyncio-extras            1.3.2
asyncpraw                 7.3.1
asyncprawcore             2.3.0
attrs                     21.4.0
backports.zoneinfo        0.2.1
beautifulsoup4            4.11.1
bidict                    0.22.0
boto3                     1.17.106
botocore                  1.20.106
Brotli                    1.0.9
cachetools                4.2.2
caio                      0.9.5
cchardet                  2.1.7
ccxt                      1.61.66
certifi                   2021.10.8
cffi                      1.15.0
chardet                   4.0.0
charset-normalizer        2.0.12
click                     8.1.3
colorlog                  4.7.2
cryptofeed                2.1.0
cryptography              37.0.2
cssselect                 1.1.0
Cython                    0.29.24
feedfinder2               0.0.4
feedparser                6.0.8
filelock                  3.7.0
Flask                     1.1.2
Flask-Caching             1.10.1
Flask-Compress            1.10.1
Flask-Login               0.5.0
Flask-SocketIO            5.0.1
Flask-WTF                 0.14.3
frozenlist                1.3.0
future                    0.18.2
gevent                    21.1.2
gevent-websocket          0.10.1
greenlet                  1.1.2
idna                      2.8
itsdangerous              2.1.2
jieba3k                   0.35.1
Jinja2                    2.11.3
jmespath                  0.10.0
joblib                    1.1.0
jsonschema                3.2.0
lxml                      4.8.0
MarkupSafe                2.1.1
multidict                 4.7.6
newspaper3k               0.2.8
nltk                      3.7
numpy                     1.21.3
oauthlib                  3.2.0
OctoBot-Backtesting       1.6.27
OctoBot-Commons           1.6.18
OctoBot-Evaluators        1.6.22
OctoBot-Services          1.2.27
OctoBot-Tentacles-Manager 2.6.3
OctoBot-Trading           1.14.2
order-book                0.4.2
packaging                 21.3
Pillow                    9.1.0
pip                       22.1
pyaes                     1.6.1
pyasn1                    0.4.8
pycares                   4.1.2
pycparser                 2.21
pyngrok                   5.0.5
pyparsing                 3.0.9
pyrsistent                0.18.1
python-dateutil           2.8.2
python-engineio           4.3.2
python-socketio           5.6.0
python-telegram-bot       13.7
python-twitter            3.5
pytz                      2022.1
pytz-deprecation-shim     0.1.0.post0
PyYAML                    6.0
regex                     2022.4.24
requests                  2.25.1
requests-file             1.5.1
requests-oauthlib         1.3.1
rsa                       4.8
s3transfer                0.4.2
setuptools                62.2.0
sgmllib3k                 1.0.0
simplifiedpytrends        1.1.2
six                       1.16.0
sortedcontainers          2.4.0
soupsieve                 2.3.2.post1
Telethon                  1.23.0
tinysegmenter             0.3
tldextract                3.3.0
tornado                   6.1
tqdm                      4.64.0
trading-backend           1.0.12
tulipy                    0.4.0
typing_extensions         4.2.0
tzdata                    2022.1
tzlocal                   4.2
update-checker            0.18.0
urllib3                   1.26.9
uvloop                    0.16.0
vaderSentiment            3.3.2
websockets                10.1
Werkzeug                  2.1.2
wheel                     0.37.1
wrapt                     1.14.1
WTForms                   2.3.3
yapic.json                1.7.2
yarl                      1.6.3
zope.event                4.5.0
zope.interface            5.4.0

**Comment by Herklos** [comment]
> using the tarball Octobot-0.4.3
> 
> ERROR on python3 start.py
> 
> ```
> from markupsafe import soft_unicode
> ```
> 
> ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/**init**.py)
> 
> DETAILS:
> 
> python3 -V Python 3.8.13
> 
> pip list Package Version
> 
> aioboto3 9.2.2 aiobotocore 1.4.2 aiodns 3.0.0 aiofile 3.7.4 aiofiles 0.6.0 aiohttp 3.8.0 aioitertools 0.10.0 aiosignal 1.2.0 aiosqlite 0.16.1 APScheduler 3.6.3 async-channel 2.0.12 async-generator 1.10 async-timeout 4.0.2 asyncio-extras 1.3.2 asyncpraw 7.3.1 asyncprawcore 2.3.0 attrs 21.4.0 backports.zoneinfo 0.2.1 beautifulsoup4 4.11.1 bidict 0.22.0 boto3 1.17.106 botocore 1.20.106 Brotli 1.0.9 cachetools 4.2.2 caio 0.9.5 cchardet 2.1.7 ccxt 1.61.66 certifi 2021.10.8 cffi 1.15.0 chardet 4.0.0 charset-normalizer 2.0.12 click 8.1.3 colorlog 4.7.2 cryptofeed 2.1.0 cryptography 37.0.2 cssselect 1.1.0 Cython 0.29.24 feedfinder2 0.0.4 feedparser 6.0.8 filelock 3.7.0 Flask 1.1.2 Flask-Caching 1.10.1 Flask-Compress 1.10.1 Flask-Login 0.5.0 Flask-SocketIO 5.0.1 Flask-WTF 0.14.3 frozenlist 1.3.0 future 0.18.2 gevent 21.1.2 gevent-websocket 0.10.1 greenlet 1.1.2 idna 2.8 itsdangerous 2.1.2 jieba3k 0.35.1 Jinja2 2.11.3 jmespath 0.10.0 joblib 1.1.0 jsonschema 3.2.0 lxml 4.8.0 MarkupSafe 2.1.1 multidict 4.7.6 newspaper3k 0.2.8 nltk 3.7 numpy 1.21.3 oauthlib 3.2.0 OctoBot-Backtesting 1.6.27 OctoBot-Commons 1.6.18 OctoBot-Evaluators 1.6.22 OctoBot-Services 1.2.27 OctoBot-Tentacles-Manager 2.6.3 OctoBot-Trading 1.14.2 order-book 0.4.2 packaging 21.3 Pillow 9.1.0 pip 22.1 pyaes 1.6.1 pyasn1 0.4.8 pycares 4.1.2 pycparser 2.21 pyngrok 5.0.5 pyparsing 3.0.9 pyrsistent 0.18.1 python-dateutil 2.8.2 python-engineio 4.3.2 python-socketio 5.6.0 python-telegram-bot 13.7 python-twitter 3.5 pytz 2022.1 pytz-deprecation-shim 0.1.0.post0 PyYAML 6.0 regex 2022.4.24 requests 2.25.1 requests-file 1.5.1 requests-oauthlib 1.3.1 rsa 4.8 s3transfer 0.4.2 setuptools 62.2.0 sgmllib3k 1.0.0 simplifiedpytrends 1.1.2 six 1.16.0 sortedcontainers 2.4.0 soupsieve 2.3.2.post1 Telethon 1.23.0 tinysegmenter 0.3 tldextract 3.3.0 tornado 6.1 tqdm 4.64.0 trading-backend 1.0.12 tulipy 0.4.0 typing_extensions 4.2.0 tzdata 2022.1 tzlocal 4.2 update-checker 0.18.0 urllib3 1.26.9 uvloop 0.16.0 vaderSentiment 3.3.2 websockets 10.1 Werkzeug 2.1.2 wheel 0.37.1 wrapt 1.14.1 WTForms 2.3.3 yapic.json 1.7.2 yarl 1.6.3 zope.event 4.5.0 zope.interface 5.4.0

Hi @danieljamesbertrand, thanks for reporting, it's fixed in the next release. It should be available very soon

**Comment by danieljamesbertrand** [comment]
When is the new release

**Comment by Herklos** [comment]
Hi, it should be fixed now with 0.4.6.
