### ISSUE TITLE
Exception ignored in: <function _ProactorBasePipeTransport.__del__ 

### ISSUE THREAD

**Issue by EgyptianM** [Drakkar-Software/OctoBot#1999]
## Step 2: Describe your environment
  * OS : [Windows.] 
  * Python Version: _____ (`python -V`)
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
I just downloaded latest release for windows and installed it but it gives me an error in the terminal although it's workin with me.

  
### Relevant code exceptions or logs:
 
```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002A6BB405D30>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by GuillaumeDSM** [comment]
Hi @EgyptianM 
This is a windows related error that has no consequence whatsoever. You can ignore it.

**Comment by EgyptianM** [comment]
Thank you
