### ISSUE TITLE
I cant deploy octobot on octeto

### ISSUE THREAD

**Issue by gdimatis** [Drakkar-Software/OctoBot#2015]

**Comment by gdimatis** [comment]
Same thing on AWS gives me error in ubuntu instance

**Comment by Herklos** [comment]
Hi, it should be fixed now we 0.4.6.

**Comment by xarthurx** [comment]
![image](https://user-images.githubusercontent.com/1921878/188167172-3c17a64b-d70a-4e32-a0f3-14eb4715d48c.png)

Nope.

**Comment by nitrocon** [comment]
following this commit: https://github.com/bitnami/bitnami-docker-wordpress/issues/103

we could try to remove the dots or find a way to have quotes and dots working

**Comment by Herklos** [comment]
Thanks for your feedback. I close this issue because we are not supporting okteto deployments anymore.
