### ISSUE TITLE
It is Failing to deploy to digitalocean

### ISSUE THREAD

**Issue by fronty77** [Drakkar-Software/OctoBot#2016]
When I try to deploy to digital ocean using the link from the website of otobot, it fails to do so, I checked the logs and found that this link https://static.octobot.online/tentacles/officials/packages/full/base/0.4.6/any_platform.zip is 404, can you fix this ?

I have a screenshot where it shows the issue

<img width="647" alt="Screenshot 2022-08-26 at 14 18 22" src="https://user-images.githubusercontent.com/111281204/186901914-90a48197-436e-4a48-b3a8-08e57020cb5d.png">

**Comment by Herklos** [comment]
Hi @fronty77, thanks for reporting, we are releasing a new version this is the reason why you have this issue. It will be fixed once when we have completed the release process (in the next 24 hours).

**Comment by Herklos** [comment]
Hi, it should be fixed now we 0.4.6.

**Comment by nitrocon** [comment]
@fronty77 Did it work?

**Comment by Herklos** [comment]
Digital ocean deployment are no longer supported, please use [OctoBot-Cloud](https://www.octobot.cloud/).
