### ISSUE TITLE
[ClockSynchronizer] Warning log for ntp in real trading mode

### ISSUE THREAD

**Issue by oijkn** [Drakkar-Software/OctoBot#2094]
* OS : Raspberry Pi Lite OS 64 bit
  * Python Version: Python 3.9.2
 
When I switch to real trading mode, a warning message appear in the event logs.
Source: `ClockSynchronizer`
Message: `Error: Time synchronization command exited with 127] command: "sudo service ntp stop && sudo ntpd -gq && sudo service ntp start"`

**Expected behavior**
No warning message and update ntp.

### Steps to reproduce:

  1. Switch to real trading mode
  2. Go to Event log menu
  
![image](https://user-images.githubusercontent.com/18188407/199603682-55a1d0b2-822e-41d8-b39e-60783ab7bacc.png)

**Comment by GuillaumeDSM** [comment]
Thanks @oijkn ! We will work on it

**Comment by GuillaumeDSM** [comment]
Fow now, if you want to disable the ClockSynchronizer, you can do it by not running your OctoBot with admin rights

**Comment by oijkn** [comment]
Actually, OctoBot is running in Docker. Which user I must set in docker-compose ?

**Comment by GuillaumeDSM** [comment]
Ok, then you can't easily disable it I guess, you can just ignore this warning. It's possible to reduce the frequency by setting the `CLOCK_REFRESH_HOURS_INTERVAL` env variable to a high number.

**Comment by oijkn** [comment]
Ok I can ignore this error.
Maybe you can add `sudo` & `ntp` package to Dockerfile ? Or use an environment variable to flag Docker mode and then do not run this command if we are in Docker mode.

Today I have another event log message, but this time is an **ERROR**, I don't know if it's related to `ntp`.

Source: `AsyncJob-_sync_clock`
Message: `Failed to run job action, exception: NotImplementedError: (2 failures in a row) (NotImplementedError)`

![image](https://user-images.githubusercontent.com/18188407/199672290-4779676a-3af5-45b8-9750-a6371d752e85.png)

**Comment by patrol114** [comment]
check service ntpsec [ service ntpsec start ]
or
sudo apt-get install ntpsec

**Comment by Herklos** [comment]
There is no longer a warning when not necessary.
