### ISSUE TITLE
[StopLossOrder] Fail to execute fill state termination

### ISSUE THREAD

**Issue by oijkn** [Drakkar-Software/OctoBot#2099]
* OS : Raspberry Pi Lite OS 64 bit
  * Python Version: Python 3.9.2
 
When I switch to real trading mode, a warning message appear in the event logs.
Source: `StopLossOrder`
Message: `Error: Fail to execute fill state termination : 'NoneType' object has no attribute 'exchange_personal_data'. (AttributeError)`

**Expected behavior**
No warning message and execute order.

### Steps to reproduce:

  1. Switch to real trading mode
  2. Go to Event log menu
  
![Screenshot_20221108_195738_edit_474119283054737.jpg](https://user-images.githubusercontent.com/18188407/200755833-433892f0-c3c0-4f81-8192-137977a6f6b6.jpg)

**Comment by GuillaumeDSM** [comment]
Thanks @oijkn, we will fix this for the next version !

**Comment by oijkn** [comment]
@GuillaumeDSM OK thank you, I sent you the log via Telegram 😊
