### ISSUE TITLE
IP Banned with standard settings

### ISSUE THREAD

**Issue by DecisiveDesignDE** [Drakkar-Software/OctoBot#2108]
## Step 1: Have you search for this issue before posting it?

I have searched and not found anything.  

## Step 2: Describe your environment
  * OS :  Ubuntu Server
  * Python Version: 3.10.6
  * Master Branch
 
## Step 3: Describe the problem:
**Describe the bug**
I have set up a new octobot, real trading with default profilt (DailyTradingMode, SimpleStrategyEvaluator ).  
To play the maximum amount of the market and get some testing in., I added a lot of coins (100+) to see if the bot would choose the best ones. I assume because of the many amount of coins, my Account/API got banned 

> DDoSProtection triggered [binance 418 I'm a teapot {"code":-1003,"msg":"Way too much request weight used; IP banned until 1668524635070. Please use the websocket for live updates to avoid bans."} (DDoSProtection)].

**Expected behavior**
The bot should respect the Binance request limit and not trigger the DDoS Protection or get me IP Banned.
How can I fix this? Just add less Coins? Or is there a limiter that I missed?

**Comment by Herklos** [comment]
Hi @DecisiveDesignDE, thanks for reporting. Did you retry with a more recent OctoBot version?
