### ISSUE TITLE
OHLCVUpdater[kucoin]  large candles 

### ISSUE THREAD

**Issue by patrol114** [Drakkar-Software/OctoBot#2122]
Hello,
 I have a question, there is an option to change candles on kucoin so that I did not have a message ?

"2022-11-25 16:13:04,977 WARNING OHLCVUpdater[kucoin] Can't initialize the required 100 historical candles: kucoin is not supporting large candles history. Using the 200 latest candles instead. "

**Comment by Herklos** [comment]
Thanks for reporting @patrol114! It's fixed in recent OctoBot version.
