### ISSUE TITLE
Error: get_supported_exchange_types() missing 1 required positional argument: 'tentacles_setup_config' (TypeError). More details in logs. 

### ISSUE THREAD

**Issue by soxito** [Drakkar-Software/OctoBot#2359]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : Ubuntu 22.04.2 LTS
  * Python Version: 3
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID:d9295f08faa4ca59e99c2d1564530515bd0c9a52da86693e0c9b7d03adf6d453 
 
## Step 3: Describe the problem:
**Describe the bug**
When i open profile and account i get error : Error: get_supported_exchange_types() missing 1 required positional argument: 'tentacles_setup_config' (TypeError). More details in logs. 

**Expected behavior**
Open account setting amd profile
### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 
```
// paste your log here
```

ERROR | WebInterfaceErrorHandler | Error when displaying page: get_supported_exchange_types()  missing 1 required positional argument: 'tentacles_setup_config'  (TypeError)
-- | -- | --

**Comment by GuillaumeDSM** [comment]
Hey @soxito, can you paste here the stacktrace you are getting in your terminal (or in your logfile) when this error happens please ?
