### ISSUE TITLE
im getting this error even if my configuration is correct  ERROR    root                 <class 'Exception'>: Error when load config

### ISSUE THREAD

**Issue by Larrycoin** [Drakkar-Software/OctoBot#240]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : [Windows, Ubuntu, Debian, Raspbian...] 
  * Python Version: _____ (`python -V`)
  * Branch: Master | Dev
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**

**Expected behavior**

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 
```
// paste your log here
```

**Comment by GuillaumeDSM** [comment]
Hello Larrycoin,
Are you sure you have your config.json file inside the root folder of the program ? 
If yes, which version are you using ?

**Comment by Larrycoin** [comment]
latest version  because I cloned it hours ago.

**Comment by GuillaumeDSM** [comment]
Are you sure you have your config.json file inside the root folder of the program ?

**Comment by Herklos** [comment]
Hello,
It's also possible to have an Json syntax error in your config.json file, so please paste your file [here](https://jsonformatter.curiousconcept.com/) to check if your Json syntax is correct.

**Comment by Larrycoin** [comment]
it is correct and I tested it there, I get this
![capture](https://user-images.githubusercontent.com/40338431/41530817-9bc29ec8-72f1-11e8-98dc-d5b4f675c6f7.PNG)

**Comment by Herklos** [comment]
Ok so the only way to have this issue with a good Json file is that your config.json file is not in the root folder.
You should have : 
...
config/
evaluators/
tools/
trading/
...
CODE_OF_CONDUCT.md
**config.json**
README.md
...

**Comment by Larrycoin** [comment]
it is in the config folder

**Comment by Herklos** [comment]
The config.json file has to be in the **root** folder

**Comment by Larrycoin** [comment]
still same error, the  above error shows when  I try this python3 start.py -p install all

**Comment by Herklos** [comment]
So you run *python3 start.py -p install all* in the **Octobot** folder with the config.json file in this folder ?

**Comment by Larrycoin** [comment]
yes but I get those errors

**Comment by Larrycoin** [comment]
I think the git has errors

**Comment by Larrycoin** [comment]
to test, send me the one you used,

**Comment by Larrycoin** [comment]
I did that sir

**Comment by Herklos** [comment]
Can you make a screenshot of your config.json please ?

**Comment by Larrycoin** [comment]
![capture](https://user-images.githubusercontent.com/40338431/41538075-98555898-730a-11e8-9443-e0e380b8e42f.PNG)

**Comment by Larrycoin** [comment]
it's still giving the error. Ok I will try

**Comment by Herklos** [comment]
You can use `git pull` to update your Octobot's repository to use the linked commit.
It will explain you what is the problem during config loading.

**Comment by Herklos** [comment]
If you have no additionnal problem to raise, I will close the issue.
