### ISSUE TITLE
Support for Arbitrage Trading 

### ISSUE THREAD

**Issue by engageub** [Drakkar-Software/OctoBot#2415]
Hi,
Could you please let me know if you plans to support triangular arbitrage trading within the same exchange or cross exchange arbitrage trading to get instant profits.
Thank you

**Comment by Herklos** [comment]
Hi @engageub. Thanks for your feedback, we really appreciate it. Is it the same idea as https://feedback.octobot.online/open-source/p/triangular-arbitrage ? If so can you please upvote the post please. We are prioritizing features with the most upvote count.

**Comment by engageub** [comment]
@Herklos.
Thank you for the response. Yes, it is what I meant along with cross exchange arbitrage and I also upvoted now. This was set to planned on July 23, 2022  by Admin. 
This strategy provides better confidence compared to other strategies. I hope this will be implemented soon.


Thank you

**Comment by Herklos** [comment]
Thanks for your vote. I hope we will be able to put this feature in our roadmap soon!
