### ISSUE TITLE
GPTEvaluator

### ISSUE THREAD

**Issue by MaxaAI** [Drakkar-Software/OctoBot#2507]
Evaluation error: Impossible to get ChatGPT prediction: GPTService service is not initialized: Configuration is missing, wrong or incomplete. This is normal if you did not configure it yet. (error: UnavailableEvaluatorError)

This error happens when i run octobot localy. I have exported my openai api key and put it inside the gpt.py but nothing works. i still get this error how can i fix this?

**Comment by GuillaumeDSM** [comment]
Hey @MaxiRadomski,
You should add your OpenAI key on the GPT service from the accounts tab, you will find more info here https://www.octobot.cloud/en/guides/octobot-interfaces/chatgpt#chatgpt-service-configuration
