### ISSUE TITLE
trade profitabliity always 0% in notification

### ISSUE THREAD

**Issue by checkiecheck** [Drakkar-Software/OctoBot#2571]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment
  *  docker octobot 1.0.8
  * DipAnalyserTradingMode 
 
## Step 3: Describe the problem:

Whenever a sell order is fullfilled, I see notifications containing 'on Bitvavo Trade profitability : +0.0000% ' while related buy order is definitly was fullfilled at lower price (at least 3%). Although its just a display thing, I would love to know the real % by notification instead of rather disappointing 0%
If it's related to specific exchange for some reason, that would be fine too to just close this issue.
**Expected behavior**
A proper value of achieved profit in the notification so I can see it kinda adheres to the trade mode parameters.

### Steps to reproduce:

  1. have strategy trigger buy order
  2. see sell orders creation at proper prices (seems good so far)
  3. wait for sell fullfillment
  
### Observed Results:

  * Trade mechanism seems good
  * just calculation of profit % (only viewbale in notification?) is alway 0.0000%

**Comment by Herklos** [comment]
Hi,

Thanks for reporting. It will be fixed in the next OctoBot version (2.0.3).

**Comment by checkiecheck** [comment]
Confirmed, seeing values now
