### ISSUE TITLE
Using Octobot in the US

### ISSUE THREAD

**Issue by choochtech** [Drakkar-Software/OctoBot#2615]
Hi,

I am using the Octobot latest opensource app via the Docker in the US.  I tried connecting to the Coninbase but it seems buggy.  Which Crypto exchange do you guys advise I use in the US ?   Binance US is not exactly like Binance by the way.

Thanks

**Comment by Herklos** [comment]
Hi,

What do you mean by Coinbase connection seems buggy? Coinbase is one of the exchanges supported by OctoBot.

**Comment by GuillaumeDSM** [comment]
The latest (2.0.2) release greatly improved the Coinbase connection, it should work much better now.
