### ISSUE TITLE
CoinEX and Bybit exchanges

### ISSUE THREAD

**Issue by hack3rcon** [Drakkar-Software/OctoBot#2687]
Hello,
Can I use the OctoBot with the CoinEX and Bybit exchanges? Any experiences?

Thank you.

**Comment by GuillaumeDSM** [comment]
Hello @hack3rcon,
Both CoinEx and Bybit are supported exchange, you can use OctoBot withthem.
You will find the list of supported exchanges on https://www.octobot.cloud/en/guides/exchanges
