### ISSUE TITLE
How can I update Octobot 2.0.2 [docker-portainer]

### ISSUE THREAD

**Issue by vlosefparmovitch** [Drakkar-Software/OctoBot#2692]
## Step 3: I did same like last update but didn't work.
- Open Custom templates 
(- edit Octobot
- Change "stable" by "lastest" ) already done for last update the 25th of may
- Update template
- Remove Octobot stack
- In Custom template, deploy again Octobot stack

But still 1.0.1 version. I don't understand why. Could you help me guys ?

Best regards and thanks

**Comment by Herklos** [comment]
Hello,

You should keep using stable but can you try to force pull the latest version of `stable` with this guide please? https://docs.portainer.io/user/docker/images/pull

**Comment by vlosefparmovitch** [comment]
I put stable but Im not success to put the latest version. I need more help ^^ 
In advanced mode that point on the 1.0.8 version not the lastest (https://hub.docker.com/r/drakkarsoftware/octobot)

Thanks, have a good day

**Comment by Herklos** [comment]
`Stable` tab is the latest stable version. It points to OctoBot 2.0.3. `Latest` tag is unstable and shouldn't be used.

You should use : 
- `drakkarsoftware/octobot:stable`
OR
- `drakkarsoftware/octobot:2.0.3`


And NOT `drakkarsoftware/octobot:latest` neither `drakkarsoftware/octobot`

**Comment by vlosefparmovitch** [comment]
Ok I changed by drakkarsoftware/octobot:2.0.3 and It works but with stable dont

Thanks guy
