### ISSUE TITLE
How do I change network settings?

### ISSUE THREAD

**Issue by hack3rcon** [Drakkar-Software/OctoBot#2734]
Hello,
How do I change network settings? I can't find network settings in `docker-compose.yml` file.

Thanks.

**Comment by GuillaumeDSM** [comment]
Hello,
Which network setting are you referring to? (web interface / exchange connection / something else ?)

**Comment by hack3rcon** [comment]
> Hello, Which network setting are you referring to? (web interface / exchange connection / something else ?)

Hello,
When I run the container, it creates a network.

**Comment by Herklos** [comment]
> > Hello, Which network setting are you referring to? (web interface / exchange connection / something else ?)
> 
> Hello, When I run the container, it creates a network.

Hello @hack3rcon. You can add the custom network you want in your docker-compose.yml file (https://docs.docker.com/compose/networking/#specify-custom-networks). 

If not provided, docker will create a default network for your containers inside the docker-compose.

**Comment by hack3rcon** [comment]
> > > Hello, Which network setting are you referring to? (web interface / exchange connection / something else ?)
> > 
> > 
> > Hello, When I run the container, it creates a network.
> 
> Hello @hack3rcon. You can add the custom network you want in your docker-compose.yml file (https://docs.docker.com/compose/networking/#specify-custom-networks).
> 
> If not provided, docker will create a default network for your containers inside the docker-compose.

Hi,
Thanks again.
Can it cause a conflict?

**Comment by hack3rcon** [comment]
> > > > > Hello, Which network setting are you referring to? (web interface / exchange connection / something else ?)
> > > > 
> > > > 
> > > > Hello, When I run the container, it creates a network.
> > > 
> > > 
> > > Hello @hack3rcon. You can add the custom network you want in your docker-compose.yml file (https://docs.docker.com/compose/networking/#specify-custom-networks).
> > > If not provided, docker will create a default network for your containers inside the docker-compose.
> > 
> > 
> > Hi, Thanks again. Can it cause a conflict?
> 
> No if you don't provide any network it can't cause a conflict. They are only used for the docker-compose's containers. You can start as many other docker-compose you want on the same computer (in different folders).

I did:
```
networks:
   default:
     ipam:
       config:
           - subnet: "172.9.0.0/16"
             gateway: "172.9.0.1"
```
But, I can't browse http://IP:80!

**Comment by Herklos** [comment]
I don't understand what you're trying do to. If you want to change the port where the OctoBot web interface is available you should have a look at docker compose `ports` attributes. You can find an example at https://docs.docker.com/compose/networking/.

**Comment by hack3rcon** [comment]
> I don't understand what you're trying do to. If you want to change the port where the OctoBot web interface is available you should have a look at docker compose `ports` attributes. You can find an example at https://docs.docker.com/compose/networking/.

Because it creates a routing table as below and I can't connect to the server:

`172.21.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-bf3cb6d36cbb`
