### ISSUE TITLE
OctoBot-Tulipy error during requirements installation

### ISSUE THREAD

**Issue by ruidazeng** [Drakkar-Software/OctoBot#2763]
Stored in directory: 
/Users/me/Library/Caches/pip/wheels/15/d7/4b/ae2b815f6dad91c0fc911270fead8e02a1d6144f214453b1e5
  Building wheel for OctoBot-Tulipy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for OctoBot-Tulipy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [393 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-13.0-arm64-cpython-312/tulipy
      copying tulipy/__init__.py -> build/lib.macosx-13.0-arm64-cpython-312/tulipy
      running build_ext
      /private/var/folders/sk/ykby6dr92313ftwf67r_mzr40000gn/T/pip-build-env-wovh07ws/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/sk/ykby6dr92313ftwf67r_mzr40000gn/T/pip-install-hhv1y9zq/octobot-tulipy_162ca441ea3745edb02ec703f7a5dc66/tulipy/lib/__init__.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from libc.limits cimport INT_MAX
      
      import numpy as np
      cimport numpy as np
      
      cimport ti
              ^
      ------------------------------------------------------------
      
      tulipy/lib/__init__.pyx:37:8: 'ti.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------

**Comment by Herklos** [comment]
Hello. OctoBot only supports python3.10

**Comment by ruidazeng** [comment]
Thank you! Is compatibility with Python 3.12 planned for the future?

**Comment by GuillaumeDSM** [comment]
Yes, OctoBot will be compatible with 3.12 in the future. However we can't yet give a timeline for this.
