### ISSUE TITLE
Binance from US

### ISSUE THREAD

**Issue by FillHK** [Drakkar-Software/OctoBot#2773]
## Step 1: Have you search for this issue before posting it?

Binance not working from USA

## Step 3: Describe the problem:
WebInterfaceErrorHandler Error when displaying page: Failed to load_symbol_markets: ExchangeNotAvailable on binance GET https://api.binance.com/api/v3/exchangeInfo 451  {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
} (error: FailedRequest)

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:
 
```
// paste your log here
```

**Comment by Herklos** [comment]
Hello, you can use Binance US if Binance is not supported for you https://www.octobot.cloud/en/guides/octobot-supported-exchanges/binanceus.
