### ISSUE TITLE
[Exchange Support] bitmex 

### ISSUE THREAD

**Issue by pudong1** [Drakkar-Software/OctoBot#278]
**Is your feature request related to a problem? Please describe.**
I want to collect to bitmex for some test and develop my own strategy. Using CCXT, it could be done. Withinin OctoBot, it seems this is feature is in lack. It would be nice if this feature could be implemented in the near feature. 

I gave a shot using current OctoBot, it seems that   the "pairs" in the config fiel, i.e.,  either   'XBTUSD' or 'BTC/USDT'  is recoginized, see more details in the log file.

Thanks in advance.
botbot1
[OctoBot.log.zip](https://github.com/Drakkar-Software/OctoBot/files/2152945/OctoBot.log.zip)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
- Add any other context or screenshots about the feature request here.
- You can link a github gist to explain the feature

**Comment by GuillaumeDSM** [comment]
Hi again,
I've looked into you log file, the line:
**WARNING OctoBot              octobot.py:140      bitmex doesn't support XBTUSD** means that this symbol is not recognized (i.e. not in ccxt's list of symbols for the given exchange).

Moreover, when setting up your config.json file, please keep in mind that you need to include the "/" in the symbol pair i.e.: BTC/USD, not BTCUSD

I hope this will help you !

**Comment by GuillaumeDSM** [comment]
By the way, we never tried OctoBot on Bitmex as you can see here [octobot-official-supported-exchanges](https://github.com/Drakkar-Software/OctoBot/wiki/Exchanges#octobot-official-supported-exchanges).
Can you share with us your experience using this exchange please ? 

Thanks a lot !

**Comment by pudong1** [comment]
Sure! The big difference of bitmex with other exchanges is Financial Leverage, up to 100x. During the oscillation phase where the direction is to be chosen, bollinger band is a very good indicator to fast trade, like several times or more in a day. I also know some people do the market maker at bitmex, which is also very profitable, particularly at oscillating phase. At the oscillating phase, the bot is a necessary tool to capture the buy/sell points. The fee is also less than others’.

By the way, I use the right pair for ccxt, now I can connect to bitmex and do the simulator trade. But it seems that the time frame only has two options, one hour or one day. I want to have more time frames, where can I get it?

We could discuss more about it, right now my time is deep middle night, I need go to sleep. For short, developing a bot for bitmex is a good investment, this is how I see it, which is also what I want to do with your help. Thank you!




2018年7月2日 星期一 +0800 00:59 发件人 notifications@github.com  <notifications@github.com>:

**Comment by GuillaumeDSM** [comment]
Thank you for your explaination and you feedback on OctoBot's interface with bitmex !

Time frames are of course first limited by the given exchange, which is an info ccxt can give and is use by OctoBot to check if a requested time frame is usable. I guess if you are asking this question it means bitmex can handle other times frames than only those 2 ones.
Time frames used by the bot depend on the used strategy:
Each strategy has a method called get_required_time_frames() which returns the list of time frames to use. In this method, you can add as many time frames as you want like in this example from the default tentacle mixed_strategies_evaluator.py: FullMixedStrategiesEvaluator:
@classmethod
    def get_required_time_frames(cls):
        return [TimeFrames.THIRTY_MINUTES,
                TimeFrames.ONE_HOUR,
                TimeFrames.TWO_HOURS,
                TimeFrames.FOUR_HOURS,
                TimeFrames.ONE_DAY]

You can get the full list of time frames in config.cst.py/TimeFrames

I hope this will help you.

**Comment by Herklos** [comment]
Hi pudong1,

Thanks for your feedback on Octobot !

I tested Bitmex in simulation mode and it seems to work, I will add it into supported exchange (in simulation) meanwhile more information about real trading.

Their is some problems with bitmex on ccxt that can impact Octobot. For example, the list of fees is empty, some symbols do not respect the *XXX/YYY* form, etc... 
Concerning **XBTUSD** it correspond to BTC/USD on ccxt.

**Comment by pudong1** [comment]
Thanks. Problem solved!

All  the best,
Bot1bot1

------ 原始信息 ------
来自: "Guillaume De Saint Martin" <notifications@github.com>
收件人: "Drakkar-Software/OctoBot" <OctoBot@noreply.github.com>
抄送人: "pudong1" <pupu35088@gmail.com>; "Author" 
<author@noreply.github.com>
发送: 2018/7/2 0:37:50
主题: Re: [Drakkar-Software/OctoBot] bitmex (#278)
