### ISSUE TITLE
[Bug][Orders] very small quantity

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#297]
[Simulator] Order(s) filled : 
- SELL_LIMIT: 812.49311 XRP at 0.00006 BTC on bitfinex: 08/07/18 11:50 
[Simulator] Order(s) canceled :
- STOP_LOSS: 812.49311 XRP at 0.00006 BTC on bitfinex: 08/07/18 11:50 

Trade profitability : -19.9116667%
Global Portfolio profitability : -4.01375% -0.0390973%

**Comment by GuillaumeDSM** [comment]
bitfinex:
![image](https://user-images.githubusercontent.com/9078616/42464767-580f4f36-83aa-11e8-9a6f-e4a6bd782433.png)

precision is there taken from price => 5 digits

on the opposite, on binance:
![image](https://user-images.githubusercontent.com/9078616/42464849-995b9120-83aa-11e8-9d51-b583e9b87822.png)

precision from exchange => 8 digits

bug is for there

**Comment by Herklos** [comment]
Action to do : 
- Explore CCXT to find the problem (because bitfinex's precision is 8 digits)
- Find another solution
