### ISSUE TITLE
[Web interface] Start / Stop trading

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#349]
- Refactor start.py
- 2 buttons in commands
- 1 icon pending start next to "Octobot"
- Don't automaticly start trading at startup
- Always start web
- New arg : "no-web"

**Comment by GuillaumeDSM** [comment]
Is this issue still relevant ? 
I think we can add a --no-trading-start argument (to force no trading at startup) and a start/stop trading in web interface, it should be enough

**Comment by Herklos** [comment]
I agree.
