### ISSUE TITLE
[Web interface] Trading mode and strategy config page

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#379]
- Choose a trading mode (disable others)
- Highligh linked strategies (with trading mode config)
- Select highlighted strategies
- config trading mode : optionnal (true/false) if some strategies are optionnal

**Comment by GuillaumeDSM** [comment]
Need to think about "config trading mode : optionnal (true/false) if some strategies are optionnal"
=> list all strategies ? strategies by groups ? by number ?
