### ISSUE TITLE
impossible to display GUI

### ISSUE THREAD

**Issue by IIChing** [Drakkar-Software/OctoBot#386]
Hi!
I am getting an error after running python3 start.py -p install all on Ubuntu (16.04.5 LTS)
`/var/www/html/OctoBot# python3 start.py -p install all
  File "start.py", line 105
    logging.error(f"{e}, impossible to display GUI")
                                                  ^
SyntaxError: invalid syntax`

How I can fix this error?

**Comment by Herklos** [comment]
Hi IIChing ! 

Can you please give me your python version ? Is it really [python 3.6](https://github.com/Drakkar-Software/OctoBot/wiki/Installation#requirements) ?

Thanks for your interest in OctoBot project
