### ISSUE TITLE
[Docker] Docker health check

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#476]
Proposition: 
- Restart container if [health check](https://howchoo.com/g/zwjhogrkywe/how-to-add-a-health-check-to-your-docker-container) fail 
         -> difficult with Flask app disabled (option -nw)

- Only use [--restart=on-failure](https://docs.docker.com/config/containers/start-containers-automatically)                           
         -> Will restart only if stopped not if some errors are raised

**Comment by Herklos** [comment]
@GuillaumeDSM

**Comment by GuillaumeDSM** [comment]
Health check: very good idea

- Indeed, no obvious why to check if working normally that I can think of.

-> use flask web interface if available ?

Why  not --restart=on-failure and add a failure return (!=0) if health check fails ?

**Comment by Herklos** [comment]
Yeah flask is a very good option to perform an health check, but we need to disable the option of disabling Flask interface. Indeed, without Flask interface I don't see any obvious way to perform that check.

Yes, you are right "--restart=on-failure" is better in this situation.

**Comment by Herklos** [comment]
Done in https://github.com/Drakkar-Software/OctoBot/commit/3434e8a987c3a00855a7ab230bffbecc293c3d5f only when Web interface is activated.
