### ISSUE TITLE
[Logger] Add traceback when 'ERROR XXXXX logging_util.py:46'

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#477]
Context : 
- When an error is raised with the logger tool there is no traceback.
Ex : 'ERROR TradesManager logging_util.py:46 dictionary changed size during iteration'

Proposition : 
- Add complete or part of the traceback when errors (maybe warnings) are catched. #416

**Comment by GuillaumeDSM** [comment]
You can have a traceback using logger.exception(e) instead of logger.error("message")
I will add it on this "dictionary changed size during iteration" specific problem

**Comment by Herklos** [comment]
I think a lot of logger.error will need this change for debug purpose.

**Comment by Herklos** [comment]
Close ?
