### ISSUE TITLE
[Exchange] Use async exchange call provided by ccxt

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#481]
Proposition : 
- Use async exchange call provided by ccxt

**Comment by GuillaumeDSM** [comment]
For which purpose ? Exchange calls are blocking on purpose in order to ensure either order creation and  portfolio update or price update.

**Comment by Herklos** [comment]
I was thinking about async on parallelisation purpose. 

For example : (without thread)
- A symbol is getting recent trades with async method and will block this symbol until methods end
- At the same time another symbol can call another async method and will block...
...

The purpose of using async here is to parallelise the same way without threads.

**Comment by Herklos** [comment]
Will be implemented in #495.
