### ISSUE TITLE
launcher_windows.exe virus total

### ISSUE THREAD

**Issue by javiertuerca** [Drakkar-Software/OctoBot#549]
Al descargar el archivo launcher_windows.exe , AVG antivirus detecta como archivo malicioso,ademas al realizar el escaneo en la web de Virus Total genera 1 deteccion  "Trojan.Generic.craqg"   [https://www.virustotal.com/es-ar/file/257f5dbce09c086bf5026ff4e288ec996f264014a1435bec1e57a44c01e5004e/analysis/1547342500/](https://www.virustotal.com/es-ar/file/257f5dbce09c086bf5026ff4e288ec996f264014a1435bec1e57a44c01e5004e/analysis/1547342500) podria publicar el valor sha256sum checksum, para verificar la descarga.

**Comment by GuillaumeDSM** [comment]
Hello javier,

We never had any antivirus problem yet, we will look into it, thanks for reporting.

**Comment by Herklos** [comment]
Hello Javier, yes it's a good idea, we will add a checksum for the next release.
