### ISSUE TITLE
Installation failed - No matching distribution

### ISSUE THREAD

**Issue by blascokoa** [Drakkar-Software/OctoBot#590]
## Step 1: Have you search for this issue before posting it? 
Yes

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : [Manjaro] 
  * Python Version: 3.7.2 (`python -V`)

## Step 3: Describe the problem:
**Describe the bug**
Error trying to install the bot.

Expected behavior**
Download the bot and install requeriments

### Steps to reproduce:

  1. python -m pip install OctoBot
  
### Observed Results:

  * What happened?
Collecting OctoBot
Could not find a version that satisfies the requirement OctoBot (from versions: )
No matching distribution found for OctoBot

**Comment by Herklos** [comment]
Yes, currently your OS (manjaro) is not listed in the setup.py file that specify OctoBot package operating system support.

You should try on a supported OS (like Ubuntu or Debian) or try with another way to install (binary or docker).

Thank you for your interest in OctoBot project !

**Comment by Herklos** [comment]
After a discussion with @GuillaumeDSM, I suggest you to install OctoBot [with python only](https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only). 

You only need to clone the repository and install python packages then you will be able to run the bot properly.

**Comment by blascokoa** [comment]
@Herklos if the issue its on the setup.py file, i will try to clone it, edit and test to install via 

`python setup.py install`

If works, will place a PR

**Comment by Herklos** [comment]
Hi @blascokoa, good idea it would be cool to test on your OS and then add it to the list of supported.
