### ISSUE TITLE
[Linux Binary] not auto opening web interface

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#620]
on linux:
when started from binary : web interface does not auto open

**Comment by Herklos** [comment]
Do you have this bug on windows ?

**Comment by GuillaumeDSM** [comment]
I don't know, i can't use the windows binary x) But with the code it works perfectly

**Comment by Herklos** [comment]
Resolved in https://github.com/Drakkar-Software/OctoBot-Binary/releases/tag/0.3.1_1-beta.
