### ISSUE TITLE
HybridTradingMode.json NOT FOUND

### ISSUE THREAD

**Issue by zm801** [Drakkar-Software/OctoBot#661]
ERROR    TentaclePackageManager Installation failed for tentacle module 'hybrid_trading_mode' (Fail to install configuration / resource : 404: Not Found: https://raw.githubusercontent.com/Drakkar-Software/OctoBot-Tentacles/master/Trading/Mode/HybridTradingMode.json)

**Comment by GuillaumeDSM** [comment]
Hello zm801,
Did you activate dev-mode in config.json ?

**Comment by zm801** [comment]
Hi Guillaume, in this installation case, "DEV-MODE":true has been added in config.json.

**Comment by Herklos** [comment]
Hi zm801,
Which is this installation case ? Did you use python sources, package, docker or binary ?

**Comment by zm801** [comment]
Hi Herklos, I used python sources.

**Comment by GuillaumeDSM** [comment]
Hi zm801,
HybridTradingMode is not ready yet, it should not be used (that's why it is in dev-mode only). This error is not preventing other mode to install, it will not affect you.
We will fix this problem in the next version, thank you for reporting the issue !

Guillaume

**Comment by Herklos** [comment]
[The problem is fixed](https://github.com/Drakkar-Software/OctoBot-Tentacles/commit/0e2b940813612ac2847a3b14e6f0c146fad53b1a), you can now try again.
