### ISSUE TITLE
[Config] Implement a wildcard for trading pairs

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#662]

**Comment by GuillaumeDSM** [comment]
To consider:
* Init wildcard evaluators in their own initialisation process in OctoBot.py
* Should OctoBot consider wildcard evaluatos AND normal evaluators at the same time ? In this case what to do with trading modes ? (Adapt current trading modes / filter available trading modes ?)
* Handle web interface and telegram interface regarding market status / price charts (maybe display nothing and have a message like 'only wildcard evaluators enables, no market analysis available) in case there are only wild card evals enabled
* Handle symbol config interface in case of activated wild card evaluators (add warning message ?)

**Comment by Werdor** [comment]
Some features done in #762
