### ISSUE TITLE
[Backtesting] handle new data formats

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#690]

**Comment by danipolo** [comment]
what data formats/file extensions are supported? I can't upload CSV.

**Comment by GuillaumeDSM** [comment]
Hello,
For now, the only supported format is zipped json. You can get a example of this format by downloading data via the web interface and unzipping it. 
However with few code changes, you can add a CSV handler if you need to

**Comment by DennyZen** [comment]
@danipolo 
did you try to make a csv handler?

**Comment by GuillaumeDSM** [comment]
We don't have any need for this so far therefore not yet but the answer above is still working. In 0.4 we are adding also a converter for our previous json format to the 0.4 one, if you want to use CSV data, you can just adapt this converter to read CSV.

**Comment by DennyZen** [comment]
@GuillaumeDSM basically, i want make backtesting with realtime data. I recorded values of realtime evaluator with Exporter into csv file(every second value) Now i am looking for a way to make a backtest using this data...
and I should add 1-second timeframe, as i understand..

**Comment by GuillaumeDSM** [comment]
You know that OctoBot has a built in data recorder, right ? 
The evaluation recording feature (I guess that's what you are using, that requires a manual entry in config.json) is only to analyse the evaluators behavior, it doesn't contain enough data to be able to run a backtesting on it. Its purpose is mostly to chart evaluator trends

**Comment by DennyZen** [comment]
@GuillaumeDSM
by "data recorder" you mean data_collector?
i know about it, but it is not writing evaluators values?
i understand that backtesting module takes data in another format than The evaluation recording feature - that why i asking..
what should i add for backtest strategy with realtime evaluator(already recorded data) ?

**Comment by GuillaumeDSM** [comment]
by "data recorder" you mean data_collector?
 => Yes, and it's evaluation neutral, it only stores exchange data that will be used in backtesting, there you can have your evaluations.

i understand that backtesting module takes data in another format than The evaluation recording feature
 => the evaluation recording feature is to record evaluations, not exchange data (that can be turned into evalutions) to record exchange data, you have the data_collector that is accessible from the web interface and that stores data in a ready to backtest format.

what should i add for backtest strategy with realtime evaluator(already recorded data) ?
 => it depends on what you mean by realtime evaluator, if you mean an evaluator extending RealtimeEvaluator, it's not implemented yet. For now backtesting supports only TA extending evaluators. If you want to test a TA extending one, you can just use the web interface to download the data you want and run a backtesting on it afterwards. If you have already recorded data not in OctoBot recording data, you will have to convert them
