### ISSUE TITLE
[Trader] Allow to start from the previous execution last move

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#731]
A setting in config.json (trading section), checkbox in web interface, unticked by default

If activated:
In a file:
* store very first startup portfolio that will be kept as a reference 
* store very first startup portfolio value and watched markets origin values
* store reference market (for consistency)

When starting the bot, if this option is selected, use this file to setup the simulator initiatial portfolio and keep profitability between instances
* Use log files to restore last portfolio

To reset this history:
* change symbol configuration
* reset button on web interface
* start the bot with --reset-history parameter
* delete file

**Comment by PKBO** [comment]
+ add / keep option to clear this history, when strategy changes
