### ISSUE TITLE
Installation procedure is missing 2 modules

### ISSUE THREAD

**Issue by JanAbraham** [Drakkar-Software/OctoBot#777]
* OS : Mac OS Mojave
  * Python Version: 3.7.3

when installing OctoBot, there are 2 modules missing: numpy and Cython. I installed them with pip install and then the installation routine went on and finished.

Maybe you want to consider adapting the installation procedure

Cheers,
Jan

**Comment by GuillaumeDSM** [comment]
Hello JanAbraham,

Did you install pre_requirements.txt ?

**Comment by JanAbraham** [comment]
Good point .. should have read that before, I guess. Case closed ;-)
