### ISSUE TITLE
[Coinbase Pro] Test OctoBot on different exchanges

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#823]

**Comment by Herklos** [comment]
This issue covers only REST connection or also simulators and / or real time testing ?

**Comment by GuillaumeDSM** [comment]
> This issue covers only REST connection or also simulators and / or real time testing ?

I tested with REST exchange:
trader simulator (candle prices, recent trades)
real trader (create, fill, cancel orders)
