### ISSUE TITLE
Cant open web interface

### ISSUE THREAD

**Issue by fabston** [Drakkar-Software/OctoBot#828]
Hi there,

I just installed your bot via docker on ubuntu 18, however I am not able to access the web interface from outside of the VPS. I changed the port to `5050` via:
    "web": {
      "port": "5050"

But the website is simply not loading. Do you have any idea what I might've done wrong?

Thanks!

**Comment by GuillaumeDSM** [comment]
Hi fabston,

Is this port exposed to the world on your VPS ?

**Comment by fabston** [comment]
Hi GuillaumeDSM,

ports should be open as I am not running any firewall...

**Comment by fabston** [comment]
`--net="host"` did the trick, all good now.

**Comment by fabston** [comment]
However Id have one more question. I setup the telegram notifications however in the log it still shows me: `Notification         Telegram disabled`. I am also not receiving any updates.

**Comment by GuillaumeDSM** [comment]
That will be fixed in the next version. For now to enable the telegram interface, start your bot with the -t parameter.

**Comment by fabston** [comment]
`touch config.json && docker run -t -v $(pwd)/config.json:/bot/octobot/config.json -v $(pwd)/logs:/bot/octobot/logs -v $(pwd)/tentacles:/bot/octobot/tentacles drakkarsoftware/octobot:latest`

Like that?

**Comment by Herklos** [comment]
Hi fabston ! For security reason it's better to not expose you port to thé World. It's up to you :wink:

**Comment by Herklos** [comment]
@fabston here you added -t as à docker param, not an octobot param. You need to add this -t param at the end of your command.

**Comment by fabston** [comment]
Thanks for letting me know lol! Well gotta change the port then.

Awesome will do that, thanks again!
