### ISSUE TITLE
[0.3.4][Exchange][REST] Officialize Kucoin and CoinBasePro support

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#830]
Can we officialize these supports by adding https://static.cryptorival.com/imgs/exchanges/kucoin/logo.png and https://cointracking.info/img/logos/coinbasepro.png to the README and support coverage on the wiki ?

_Originally posted by @Herklos in https://github.com/Drakkar-Software/OctoBot/pull/819#issuecomment-487271182_

**Comment by GuillaumeDSM** [comment]
yes
