### ISSUE TITLE
ModuleNotFoundError: No module named 'tentacles_manager'

### ISSUE THREAD

**Issue by clickbrain** [Drakkar-Software/OctoBot#854]
## Step 1: Have you search for this issue before posting it?
I did search and two issues I found were closed and did not address the issue. 

## Step 2: Describe your environment
  * OS : MacOS
  * Python Version: Python 3.7.3 - running Anaconda
  * In case you are not using a binary version:
    * Branch: Master | Dev
    * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
**Describe the bug**
Following the Python install instructions here: 
https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only

**Expected behavior**
Complete install

### Steps to reproduce:

  1. git clone https://github.com/Drakkar-Software/OctoBot - WORKED
  2. cd OctoBot - WORKED
  3. cp ./config/default_config.json ./config.json - WORKED - no message
  4. pip3 install -r pre_requirements.txt - WORKED
  5. pip3 install -r requirements.txt 
  6. start.py -p install all
```
Traceback (most recent call last):
  File "start.py", line 18, in <module>
    from tools.commands import Commands
  File "/Users/bradnickel/Documents/octobot/OctoBot/tools/commands.py", line 24, in <module>
    from tentacles_manager.tentacle_creator.tentacle_creator import TentacleCreator
ModuleNotFoundError: No module named 'tentacles_manager'
```

  
### Observed Results:
Error that tentacles manager not found. 

Tried start.py and got same erro. 

### Relevant code exceptions or logs:
 
```
// paste your log here
```

**Comment by Herklos** [comment]
Hi @clickbrain ! 
Did `pip3 install -r requirements.txt` worked ?

It's seems that the python you used to run `start.py -p install all` or only `start.py` does not have OctoBot-Tentacles-Manager package installed.

If all the install succeed there is 2 possible way to solve your issue : 
- You used an incorrect python to install or run. You need to check which python your `pip3` is using and also which python you used to run `start.py`
- You need to install manually the package by using `pip3 install OctoBot-Tentacles-Manager` but it shouldn't be necessary.

Do not hesitate to comment this issue with your results. Thanks for using OctoBot !

**Comment by Jimmy-Carbone** [comment]
Try `python -m pip install -r requirements.txt`  or `python3.7 -m pip install -r requirements.txt`

**Comment by clickbrain** [comment]
Sorry for the delay in coming back to this. Been buried. Ran with this: 

> python3.7 -m pip install -r requirements.txt 

and it did the trick. Thank you for your help.

**Comment by GuillaumeDSM** [comment]
Closing this, [wiki](https://github.com/Drakkar-Software/OctoBot/wiki/Developer-Installation) and [wiki](https://github.com/Drakkar-Software/OctoBot/wiki/With-Python-only) updated
