### ISSUE TITLE
[Web interface] display of very small numbers digits

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#896]
display real val, not approx

**Comment by mouhamed-o** [comment]
HI, I use octoBot to trade on binance . On web UI or telegram command octoBot display small amount

**Comment by GuillaumeDSM** [comment]
Hi,
Can you upload a screenshot please ?

**Comment by mouhamed-o** [comment]
<img width="1639" alt="Capture d’écran 2019-06-15 à 17 22 59" src="https://user-images.githubusercontent.com/9486154/59553226-62608280-8f92-11e9-9179-8ca6fccb333a.png">

**Comment by GuillaumeDSM** [comment]
Thanks for the screenshot.
However, I'm not sure I understand the problem.
[Here](https://github.com/Drakkar-Software/OctoBot/pull/897) you can find screenshots of the current issue fix
