### ISSUE TITLE
[Simulator] freeze on staggered orders simulation

### ISSUE THREAD

**Issue by GuillaumeDSM** [Drakkar-Software/OctoBot#899]
seems to suddenly stop => deadlock ?
apparently, happens only on staggered orders, in simulation on windows (to confirm)
[OctoBot.log.1.txt](https://github.com/Drakkar-Software/OctoBot/files/3195019/OctoBot.log.1.txt)

**Comment by Herklos** [comment]
Hum, what about this line : 
```OrdersManagerSimulator[binance] logging_util.py:58       Failed to get recent trade: binance GET https://api.binance.com/api/v1/aggTrades?symbol=...```

**Comment by GuillaumeDSM** [comment]
It freezes more than 14h after, I don't think it's the the problem. this happens sometimes not an issue in my opinion, unfortunately

**Comment by Herklos** [comment]
Yes it's more a binance / REST exchange issue. I don't have any idea concerning this freeze.

**Comment by GuillaumeDSM** [comment]
fixed by https://github.com/Drakkar-Software/OctoBot/wiki/Installation-Troubleshoot#octobot-freeze
