### ISSUE TITLE
[Bug] Config checker failed when using wildcard on pairs

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot#900]
config_schema.json doesn't properly describe the wildcard implementation. 

Bug found by AlgoLuke.

**Comment by GuillaumeDSM** [comment]
I suggest modifying the wildcard config to ["*"] in order to keep the array format

**Comment by Herklos** [comment]
> I suggest modifying the wildcard config to ["*"] in order to keep the array format

Yes but what about something like `[LTC/BNB, *, ETH/USDT]` ?

**Comment by GuillaumeDSM** [comment]
We can make it invalid: only allow ["*"] or ["xxx/zzz", "yyy/xxx"] but no mix, what do you think ?
