### ISSUE TITLE
how to use shadowsocks-R

### ISSUE THREAD

**Issue by TopSun2010** [Drakkar-Software/OctoBot#957]
I can't use the binance API。whether I open SSR or not.
Please tell me how to use proxy with OCTOBOT

**Comment by GuillaumeDSM** [comment]
Hello,
Sorry for the late answer but we never got this need yet and for now it's not our priority to handle proxies. 
However if you have an idea on how this can be done, please feel free to contribute to the project :)

**Comment by NovaCygni** [comment]
> Hello,
> Sorry for the late answer but we never got this need yet and for now it's not our priority to handle proxies.
> However if you have an idea on how this can be done, please feel free to contribute to the project :)

Believe this was added a couple months ago in a version I tweaked for a friends setup, ill have a ganders when I eventually get a free moment and push the code changes.

**Comment by GuillaumeDSM** [comment]
That would be great @NovaCygni !
Don't hesitate to open a pull request when you have time :)

**Comment by kuskyfei** [comment]
> > Hello,
> > Sorry for the late answer but we never got this need yet and for now it's not our priority to handle proxies.
> > However if you have an idea on how this can be done, please feel free to contribute to the project :)
> 
> Believe this was added a couple months ago in a version I tweaked for a friends setup, ill have a ganders when I eventually get a free moment and push the code changes.

Have you solved this question? I also want use proxy in this project,can you help me ?THX!

**Comment by kuskyfei** [comment]
> > Hello,
> > Sorry for the late answer but we never got this need yet and for now it's not our priority to handle proxies.
> > However if you have an idea on how this can be done, please feel free to contribute to the project :)
> 
> Believe this was added a couple months ago in a version I tweaked for a friends setup, ill have a ganders when I eventually get a free moment and push the code changes.

I noticed that this project use ccxt library , so I think it can use a proxy, but I'm not sure how to add it .Help !

**Comment by GuillaumeDSM** [comment]
Hello !
Yes, it looks like ccxt supports proxies, I suggest you have a look at [this issue](https://github.com/ccxt/ccxt/issues/5742) and [this part of the ccxt manual](https://github.com/ccxt/ccxt/wiki/Install#python-35-asyncioaiohttp-proxy).

Once you know how to tell ccxt to use a proxy, you will find the ccxt exchange initilisalization within OctoBot in 
```
trading/exchanges/rest_exchanges/rest_exchange.py line 86
```

**Comment by kuskyfei** [comment]
> Hello !
> Yes, it looks like ccxt supports proxies, I suggest you have a look at [this issue](https://github.com/ccxt/ccxt/issues/5742) and [this part of the ccxt manual](https://github.com/ccxt/ccxt/wiki/Install#python-35-asyncioaiohttp-proxy).
> 
> Once you know how to tell ccxt to use a proxy, you will find the ccxt exchange initilisalization within OctoBot in
> 
> ```
> trading/exchanges/rest_exchanges/rest_exchange.py line 86
> ```

THX！It worked！

**Comment by GuillaumeDSM** [comment]
Great 💯

**Comment by Herklos** [comment]
Closed for no update from owner.
